// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package db

import (
	"context"
	"database/sql"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (country_name, country_code, currency_id)
VALUES ($1, $2, $3)
RETURNING country_id, country_name, currency_id, updated_at, created_at, country_code
`

type CreateCountryParams struct {
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, arg.CountryName, arg.CountryCode, arg.CurrencyID)
	var i Country
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE country_id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, countryID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCountry, countryID)
	return err
}

const getAllCountries = `-- name: GetAllCountries :many
SELECT country_id, country_name, country_code, currency_id, updated_at, created_at FROM countries
ORDER BY country_id
`

type GetAllCountriesRow struct {
	CountryID   int32
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
	UpdatedAt   sql.NullTime
	CreatedAt   sql.NullTime
}

func (q *Queries) GetAllCountries(ctx context.Context) ([]GetAllCountriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCountriesRow
	for rows.Next() {
		var i GetAllCountriesRow
		if err := rows.Scan(
			&i.CountryID,
			&i.CountryName,
			&i.CountryCode,
			&i.CurrencyID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountriesByCurrencyID = `-- name: GetCountriesByCurrencyID :many
SELECT country_id, country_name, country_code, currency_id, updated_at, created_at FROM countries
WHERE currency_id = $1
ORDER BY country_id
`

type GetCountriesByCurrencyIDRow struct {
	CountryID   int32
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
	UpdatedAt   sql.NullTime
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCountriesByCurrencyID(ctx context.Context, currencyID int32) ([]GetCountriesByCurrencyIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCountriesByCurrencyID, currencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountriesByCurrencyIDRow
	for rows.Next() {
		var i GetCountriesByCurrencyIDRow
		if err := rows.Scan(
			&i.CountryID,
			&i.CountryName,
			&i.CountryCode,
			&i.CurrencyID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT country_id, country_name, country_code, currency_id, updated_at, created_at FROM countries 
WHERE country_code = $1 LIMIT 1
`

type GetCountryByCodeRow struct {
	CountryID   int32
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
	UpdatedAt   sql.NullTime
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCountryByCode(ctx context.Context, countryCode sql.NullString) (GetCountryByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCountryByCode, countryCode)
	var i GetCountryByCodeRow
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CountryCode,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT country_id, country_name, country_code, currency_id, updated_at, created_at FROM countries 
WHERE country_id = $1 LIMIT 1
`

type GetCountryByIDRow struct {
	CountryID   int32
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
	UpdatedAt   sql.NullTime
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCountryByID(ctx context.Context, countryID int32) (GetCountryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCountryByID, countryID)
	var i GetCountryByIDRow
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CountryCode,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET 
    country_name = COALESCE($2, country_name),
    country_code = COALESCE($3, country_code),
    currency_id = COALESCE($4, currency_id),
    updated_at = CURRENT_TIMESTAMP
WHERE country_id = $1
RETURNING country_id, country_name, currency_id, updated_at, created_at, country_code
`

type UpdateCountryParams struct {
	CountryID   int32
	CountryName string
	CountryCode sql.NullString
	CurrencyID  int32
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, updateCountry,
		arg.CountryID,
		arg.CountryName,
		arg.CountryCode,
		arg.CurrencyID,
	)
	var i Country
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}
