// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, updated_at, created_at, type_id
`

type CreateExchangeRateParams struct {
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, createExchangeRate,
		arg.RateValue,
		arg.SourceCurrencyID,
		arg.DestinationCurrencyID,
		arg.ValidFromDate,
		arg.ValidToDate,
		arg.SourceID,
		arg.TypeID,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TypeID,
	)
	return i, err
}

const deleteAllExchangeRates = `-- name: DeleteAllExchangeRates :exec
DELETE FROM exchange_rates
`

func (q *Queries) DeleteAllExchangeRates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllExchangeRates)
	return err
}

const deleteExchangeRate = `-- name: DeleteExchangeRate :exec
DELETE FROM exchange_rates
WHERE rate_id = $1
`

func (q *Queries) DeleteExchangeRate(ctx context.Context, rateID int32) error {
	_, err := q.db.ExecContext(ctx, deleteExchangeRate, rateID)
	return err
}

const getAllExchangeRatesToday = `-- name: GetAllExchangeRatesToday :many
SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
FROM exchange_rates
WHERE created_at >= (SELECT NOW()::date)
AND source_currency_id = $1
ORDER BY rate_id DESC
LIMIT $2
`

type GetAllExchangeRatesTodayParams struct {
	SourceCurrencyID int32
	Limit            int32
}

type GetAllExchangeRatesTodayRow struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

func (q *Queries) GetAllExchangeRatesToday(ctx context.Context, arg GetAllExchangeRatesTodayParams) ([]GetAllExchangeRatesTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExchangeRatesToday, arg.SourceCurrencyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExchangeRatesTodayRow
	for rows.Next() {
		var i GetAllExchangeRatesTodayRow
		if err := rows.Scan(
			&i.RateID,
			&i.RateValue,
			&i.SourceCurrencyID,
			&i.DestinationCurrencyID,
			&i.ValidFromDate,
			&i.ValidToDate,
			&i.SourceID,
			&i.TypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExchangeRatesTodayNormalised = `-- name: GetAllExchangeRatesTodayNormalised :many

SELECT DISTINCT ON (er.destination_currency_id, er.source_id, er.type_id)
  er.rate_id,
  er.rate_value,
  sc.currency_code AS source_currency_code,
  dc.currency_code AS destination_currency_code,
  er.valid_from_date,
  rs.source_code AS rate_source_code,
  ert.type_name AS type_name,
  er.updated_at
FROM exchange_rates er
JOIN currencies sc ON er.source_currency_id = sc.currency_id
JOIN currencies dc ON er.destination_currency_id = dc.currency_id
LEFT JOIN rate_sources rs ON er.source_id = rs.source_id
LEFT JOIN exchange_rate_types ert ON er.type_id = ert.type_id
WHERE er.source_currency_id = $1
ORDER BY
  er.destination_currency_id,
  er.source_id,
  er.type_id,
  er.updated_at DESC NULLS LAST
LIMIT $2
`

type GetAllExchangeRatesTodayNormalisedParams struct {
	SourceCurrencyID int32
	Limit            int32
}

type GetAllExchangeRatesTodayNormalisedRow struct {
	RateID                  int32
	RateValue               string
	SourceCurrencyCode      string
	DestinationCurrencyCode string
	ValidFromDate           time.Time
	RateSourceCode          sql.NullString
	TypeName                sql.NullString
	UpdatedAt               sql.NullTime
}

// $2: page size
func (q *Queries) GetAllExchangeRatesTodayNormalised(ctx context.Context, arg GetAllExchangeRatesTodayNormalisedParams) ([]GetAllExchangeRatesTodayNormalisedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExchangeRatesTodayNormalised, arg.SourceCurrencyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExchangeRatesTodayNormalisedRow
	for rows.Next() {
		var i GetAllExchangeRatesTodayNormalisedRow
		if err := rows.Scan(
			&i.RateID,
			&i.RateValue,
			&i.SourceCurrencyCode,
			&i.DestinationCurrencyCode,
			&i.ValidFromDate,
			&i.RateSourceCode,
			&i.TypeName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExchangeRateByID = `-- name: GetExchangeRateByID :one
SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
FROM exchange_rates
WHERE rate_id = $1 
LIMIT 1
`

type GetExchangeRateByIDRow struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

func (q *Queries) GetExchangeRateByID(ctx context.Context, rateID int32) (GetExchangeRateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRateByID, rateID)
	var i GetExchangeRateByIDRow
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.TypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHistoricalData = `-- name: GetHistoricalData :many
WITH bucketed AS (
  SELECT 
    er.rate_value,
    er.updated_at,
    er.type_id,
    NTILE($5) OVER (ORDER BY er.updated_at) AS bucket
  FROM exchange_rates er
  WHERE er.source_currency_id = $1
    AND er.destination_currency_id = $2
    AND er.source_id = $3
    AND er.updated_at >= $4
)
SELECT DISTINCT ON (bucket) rate_value, updated_at, type_id
FROM bucketed
ORDER BY bucket, updated_at DESC
`

type GetHistoricalDataParams struct {
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	SourceID              sql.NullInt32
	UpdatedAt             sql.NullTime
	Ntile                 int32
}

type GetHistoricalDataRow struct {
	RateValue string
	UpdatedAt sql.NullTime
	TypeID    sql.NullInt32
}

// Fetches evenly distributed exchange rate data points across a time range.
// Returns up to num_data_points evenly spaced samples from the time range [start_time, now).
// Parameters:
//
//	$1: source_currency_id
//	$2: destination_currency_id
//	$3: source_id
//	$4: start_time (UpdatedAt in struct)
//	$5: num_data_points (Ntile in struct)
func (q *Queries) GetHistoricalData(ctx context.Context, arg GetHistoricalDataParams) ([]GetHistoricalDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoricalData,
		arg.SourceCurrencyID,
		arg.DestinationCurrencyID,
		arg.SourceID,
		arg.UpdatedAt,
		arg.Ntile,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoricalDataRow
	for rows.Next() {
		var i GetHistoricalDataRow
		if err := rows.Scan(&i.RateValue, &i.UpdatedAt, &i.TypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExchangeRate = `-- name: UpdateExchangeRate :one
UPDATE exchange_rates
SET 
    rate_value = COALESCE($2, rate_value),
    source_currency_id = COALESCE($3, source_currency_id),
    destination_currency_id = COALESCE($4, destination_currency_id),
    valid_from_date = COALESCE($5, valid_from_date),
    valid_to_date = COALESCE($6, valid_to_date),
    source_id = COALESCE($7, source_id),
    type_id = COALESCE($8, type_id),
    updated_at = CURRENT_TIMESTAMP
WHERE rate_id = $1
RETURNING rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, updated_at, created_at, type_id
`

type UpdateExchangeRateParams struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
}

func (q *Queries) UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, updateExchangeRate,
		arg.RateID,
		arg.RateValue,
		arg.SourceCurrencyID,
		arg.DestinationCurrencyID,
		arg.ValidFromDate,
		arg.ValidToDate,
		arg.SourceID,
		arg.TypeID,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TypeID,
	)
	return i, err
}
