// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, updated_at, created_at, type_id
`

type CreateExchangeRateParams struct {
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, createExchangeRate,
		arg.RateValue,
		arg.SourceCurrencyID,
		arg.DestinationCurrencyID,
		arg.ValidFromDate,
		arg.ValidToDate,
		arg.SourceID,
		arg.TypeID,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TypeID,
	)
	return i, err
}

const deleteAllExchangeRates = `-- name: DeleteAllExchangeRates :exec
DELETE FROM exchange_rates
`

func (q *Queries) DeleteAllExchangeRates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllExchangeRates)
	return err
}

const deleteExchangeRate = `-- name: DeleteExchangeRate :exec
DELETE FROM exchange_rates
WHERE rate_id = $1
`

func (q *Queries) DeleteExchangeRate(ctx context.Context, rateID int32) error {
	_, err := q.db.ExecContext(ctx, deleteExchangeRate, rateID)
	return err
}

const getAllExchangeRatesToday = `-- name: GetAllExchangeRatesToday :many
SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
FROM exchange_rates
WHERE created_at >= (SELECT NOW()::date)
AND source_currency_id = $1
ORDER BY rate_id DESC
LIMIT $2
`

type GetAllExchangeRatesTodayParams struct {
	SourceCurrencyID int32
	Limit            int32
}

type GetAllExchangeRatesTodayRow struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

func (q *Queries) GetAllExchangeRatesToday(ctx context.Context, arg GetAllExchangeRatesTodayParams) ([]GetAllExchangeRatesTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExchangeRatesToday, arg.SourceCurrencyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExchangeRatesTodayRow
	for rows.Next() {
		var i GetAllExchangeRatesTodayRow
		if err := rows.Scan(
			&i.RateID,
			&i.RateValue,
			&i.SourceCurrencyID,
			&i.DestinationCurrencyID,
			&i.ValidFromDate,
			&i.ValidToDate,
			&i.SourceID,
			&i.TypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExchangeRateByID = `-- name: GetExchangeRateByID :one
SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
FROM exchange_rates
WHERE rate_id = $1 
LIMIT 1
`

type GetExchangeRateByIDRow struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

func (q *Queries) GetExchangeRateByID(ctx context.Context, rateID int32) (GetExchangeRateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRateByID, rateID)
	var i GetExchangeRateByIDRow
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.TypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExchangeRate = `-- name: UpdateExchangeRate :one





UPDATE exchange_rates
SET 
    rate_value = COALESCE($2, rate_value),
    source_currency_id = COALESCE($3, source_currency_id),
    destination_currency_id = COALESCE($4, destination_currency_id),
    valid_from_date = COALESCE($5, valid_from_date),
    valid_to_date = COALESCE($6, valid_to_date),
    source_id = COALESCE($7, source_id),
    type_id = COALESCE($8, type_id),
    updated_at = CURRENT_TIMESTAMP
WHERE rate_id = $1
RETURNING rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, updated_at, created_at, type_id
`

type UpdateExchangeRateParams struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	TypeID                sql.NullInt32
}

// $2: page size
// -- name: GetExchangeRatesByTypeAfterID :many
// SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
// FROM exchange_rates
// WHERE created_at >= (SELECT NOW()::date)
//
//	AND rate_id > $2
//
// ORDER BY rate_id
// LIMIT $3;
// -- name: GetExchangeRatesByCurrencyPairAfter :many
// SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
// FROM exchange_rates
// WHERE source_currency_id = $1
//
//	AND destination_currency_id = $2
//	AND (
//	  valid_from_date < $3
//	  OR (valid_from_date = $3 AND rate_id < $4)
//	)
//
// ORDER BY valid_from_date DESC, rate_id DESC
// LIMIT $5;
// -- name: GetLatestRatesByPairSourceType :many
// WITH ranked AS (
//
//	SELECT
//	  er.rate_id,
//	  er.rate_value,
//	  er.source_currency_id,
//	  er.destination_currency_id,
//	  er.source_id,
//	  er.type_id,
//	  er.valid_from_date,
//	  er.updated_at,
//	  ROW_NUMBER() OVER (
//	    PARTITION BY er.source_id, er.source_currency_id, er.destination_currency_id, er.type_id
//	    ORDER BY er.valid_from_date DESC, er.rate_id DESC
//	  ) AS rn
//	FROM exchange_rates er
//	WHERE er.source_currency_id = $1
//	  AND er.destination_currency_id = $2
//
// )
// SELECT
//
//	rate_id, rate_value, source_currency_id, destination_currency_id, source_id, type_id, valid_from_date, updated_at
//
// FROM ranked
// WHERE rn = 1
// ORDER BY source_id, type_id;
// -- name: GetExchangeRatesByCurrencyPairLatest :many
// SELECT rate_id, rate_value, source_currency_id, destination_currency_id, valid_from_date, valid_to_date, source_id, type_id, created_at, updated_at
// FROM exchange_rates
// WHERE source_currency_id = $1
//
//	AND destination_currency_id = $2
//
// ORDER BY valid_from_date DESC, rate_id DESC
// LIMIT $3;
func (q *Queries) UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, updateExchangeRate,
		arg.RateID,
		arg.RateValue,
		arg.SourceCurrencyID,
		arg.DestinationCurrencyID,
		arg.ValidFromDate,
		arg.ValidToDate,
		arg.SourceID,
		arg.TypeID,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.RateID,
		&i.RateValue,
		&i.SourceCurrencyID,
		&i.DestinationCurrencyID,
		&i.ValidFromDate,
		&i.ValidToDate,
		&i.SourceID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TypeID,
	)
	return i, err
}
