// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate_type.sql

package db

import (
	"context"
)

const createExchangeRateType = `-- name: CreateExchangeRateType :one
INSERT INTO exchange_rate_types (type_name)
VALUES ($1)
RETURNING type_id, type_name
`

func (q *Queries) CreateExchangeRateType(ctx context.Context, typeName string) (ExchangeRateType, error) {
	row := q.db.QueryRowContext(ctx, createExchangeRateType, typeName)
	var i ExchangeRateType
	err := row.Scan(&i.TypeID, &i.TypeName)
	return i, err
}

const deleteExchangeRateType = `-- name: DeleteExchangeRateType :exec
DELETE FROM exchange_rate_types
WHERE type_id = $1
`

func (q *Queries) DeleteExchangeRateType(ctx context.Context, typeID int32) error {
	_, err := q.db.ExecContext(ctx, deleteExchangeRateType, typeID)
	return err
}

const getExchangeRateType = `-- name: GetExchangeRateType :one
SELECT type_id, type_name FROM exchange_rate_types
WHERE type_id = $1 LIMIT 1
`

func (q *Queries) GetExchangeRateType(ctx context.Context, typeID int32) (ExchangeRateType, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRateType, typeID)
	var i ExchangeRateType
	err := row.Scan(&i.TypeID, &i.TypeName)
	return i, err
}

const getExchangeRateTypeByName = `-- name: GetExchangeRateTypeByName :one
SELECT type_id, type_name FROM exchange_rate_types
WHERE type_name = $1 LIMIT 1
`

func (q *Queries) GetExchangeRateTypeByName(ctx context.Context, typeName string) (ExchangeRateType, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRateTypeByName, typeName)
	var i ExchangeRateType
	err := row.Scan(&i.TypeID, &i.TypeName)
	return i, err
}

const listExchangeRateTypes = `-- name: ListExchangeRateTypes :many
SELECT type_id, type_name FROM exchange_rate_types
ORDER BY type_name
`

func (q *Queries) ListExchangeRateTypes(ctx context.Context) ([]ExchangeRateType, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRateTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRateType
	for rows.Next() {
		var i ExchangeRateType
		if err := rows.Scan(&i.TypeID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExchangeRateType = `-- name: UpdateExchangeRateType :one
UPDATE exchange_rate_types
SET type_name = $2
WHERE type_id = $1
RETURNING type_id, type_name
`

type UpdateExchangeRateTypeParams struct {
	TypeID   int32
	TypeName string
}

func (q *Queries) UpdateExchangeRateType(ctx context.Context, arg UpdateExchangeRateTypeParams) (ExchangeRateType, error) {
	row := q.db.QueryRowContext(ctx, updateExchangeRateType, arg.TypeID, arg.TypeName)
	var i ExchangeRateType
	err := row.Scan(&i.TypeID, &i.TypeName)
	return i, err
}
