// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateCurrencyPreference(ctx context.Context, arg CreateCurrencyPreferenceParams) (UserCurrencyPreference, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error)
	CreateExchangeRateType(ctx context.Context, typeName string) (ExchangeRateType, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRateSource(ctx context.Context, arg CreateRateSourceParams) (RateSource, error)
	CreateRateSourcePreference(ctx context.Context, arg CreateRateSourcePreferenceParams) (UserRateSourcePreference, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteAllExchangeRates(ctx context.Context) error
	DeleteCountry(ctx context.Context, countryID int32) error
	DeleteCurrency(ctx context.Context, currencyID int32) error
	DeleteCurrencyPreference(ctx context.Context, arg DeleteCurrencyPreferenceParams) error
	DeleteExchangeRate(ctx context.Context, rateID int32) error
	DeleteExchangeRateType(ctx context.Context, typeID int32) error
	DeletePayment(ctx context.Context, paymentID int32) error
	DeleteRateSource(ctx context.Context, sourceID int32) error
	DeleteRateSourcePreference(ctx context.Context, arg DeleteRateSourcePreferenceParams) error
	DeleteSubscriptionPlan(ctx context.Context, planID int32) error
	DeleteUserByEmail(ctx context.Context, email string) error
	DeleteUserByID(ctx context.Context, userID int32) error
	DeleteUserSubscription(ctx context.Context, subscriptionID int32) error
	GetActiveSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	GetActiveUserSubscriptionByUserID(ctx context.Context, userID int32) (UserSubscription, error)
	GetAllCountries(ctx context.Context) ([]GetAllCountriesRow, error)
	GetAllCurrencies(ctx context.Context) ([]GetAllCurrenciesRow, error)
	GetAllCurrencyCodesAndNames(ctx context.Context) ([]GetAllCurrencyCodesAndNamesRow, error)
	GetAllCurrencyPreferences(ctx context.Context, arg GetAllCurrencyPreferencesParams) ([]UserCurrencyPreference, error)
	GetAllExchangeRatesToday(ctx context.Context, arg GetAllExchangeRatesTodayParams) ([]GetAllExchangeRatesTodayRow, error)
	// $2: page size
	GetAllExchangeRatesTodayNormalised(ctx context.Context, arg GetAllExchangeRatesTodayNormalisedParams) ([]GetAllExchangeRatesTodayNormalisedRow, error)
	GetAllPayments(ctx context.Context) ([]Payment, error)
	GetAllRateSourcePreferences(ctx context.Context, arg GetAllRateSourcePreferencesParams) ([]UserRateSourcePreference, error)
	GetAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	GetAllUserSubscriptions(ctx context.Context) ([]UserSubscription, error)
	GetCountriesByCurrencyID(ctx context.Context, currencyID int32) ([]GetCountriesByCurrencyIDRow, error)
	GetCountryByCode(ctx context.Context, countryCode sql.NullString) (GetCountryByCodeRow, error)
	GetCountryByID(ctx context.Context, countryID int32) (GetCountryByIDRow, error)
	GetCurrencyByID(ctx context.Context, currencyID int32) (GetCurrencyByIDRow, error)
	GetCurrencyPreferencesByCurrencyID(ctx context.Context, arg GetCurrencyPreferencesByCurrencyIDParams) ([]UserCurrencyPreference, error)
	GetCurrencyPreferencesByUserID(ctx context.Context, arg GetCurrencyPreferencesByUserIDParams) ([]UserCurrencyPreference, error)
	GetExchangeRateByID(ctx context.Context, rateID int32) (GetExchangeRateByIDRow, error)
	GetExchangeRateType(ctx context.Context, typeID int32) (ExchangeRateType, error)
	GetExchangeRateTypeByName(ctx context.Context, typeName string) (ExchangeRateType, error)
	// Fetches evenly distributed exchange rate data points across a time range.
	// Returns up to num_data_points evenly spaced samples from the time range [start_time, now).
	// Parameters:
	//   $1: source_currency_id
	//   $2: destination_currency_id
	//   $3: source_id
	//   $4: start_time (UpdatedAt in struct)
	//   $5: type_id
	//   $6: num_data_points
	GetHistoricalData(ctx context.Context, arg GetHistoricalDataParams) ([]GetHistoricalDataRow, error)
	GetPaymentByID(ctx context.Context, paymentID int32) (Payment, error)
	GetPaymentByTransactionID(ctx context.Context, transactionID sql.NullString) (Payment, error)
	GetPaymentsByStatus(ctx context.Context, paymentStatus sql.NullString) ([]Payment, error)
	GetPaymentsByUserID(ctx context.Context, userID int32) ([]Payment, error)
	GetRateSourceByCode(ctx context.Context, sourceCode sql.NullString) (GetRateSourceByCodeRow, error)
	GetRateSourceByID(ctx context.Context, sourceID int32) (GetRateSourceByIDRow, error)
	GetRateSourcePreferencesBySourceID(ctx context.Context, arg GetRateSourcePreferencesBySourceIDParams) ([]UserRateSourcePreference, error)
	GetRateSourcePreferencesByUserID(ctx context.Context, arg GetRateSourcePreferencesByUserIDParams) ([]UserRateSourcePreference, error)
	GetSessionByID(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetSubscriptionPlanByID(ctx context.Context, planID int32) (SubscriptionPlan, error)
	GetSubscriptionPlanByName(ctx context.Context, planName string) (SubscriptionPlan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserSubscriptionByID(ctx context.Context, subscriptionID int32) (UserSubscription, error)
	GetUserSubscriptionsByStatus(ctx context.Context, status sql.NullString) ([]UserSubscription, error)
	GetUserSubscriptionsByUserID(ctx context.Context, userID int32) ([]UserSubscription, error)
	ListExchangeRateTypes(ctx context.Context) ([]ExchangeRateType, error)
	ListRateSourceMetadata(ctx context.Context) ([]ListRateSourceMetadataRow, error)
	ListRateSources(ctx context.Context) ([]ListRateSourcesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateCurrencyPreference(ctx context.Context, arg UpdateCurrencyPreferenceParams) (UserCurrencyPreference, error)
	UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (ExchangeRate, error)
	UpdateExchangeRateType(ctx context.Context, arg UpdateExchangeRateTypeParams) (ExchangeRateType, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateRateSource(ctx context.Context, arg UpdateRateSourceParams) (RateSource, error)
	UpdateRateSourcePreference(ctx context.Context, arg UpdateRateSourcePreferenceParams) (UserRateSourcePreference, error)
	UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmailVerified(ctx context.Context, userID int32) (User, error)
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
