// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_source.sql

package db

import (
	"context"
	"database/sql"
)

const createRateSource = `-- name: CreateRateSource :one
INSERT INTO rate_sources (source_name, source_link, source_country, source_status, source_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code
`

type CreateRateSourceParams struct {
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) CreateRateSource(ctx context.Context, arg CreateRateSourceParams) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, createRateSource,
		arg.SourceName,
		arg.SourceLink,
		arg.SourceCountry,
		arg.SourceStatus,
		arg.SourceCode,
	)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}

const deleteRateSource = `-- name: DeleteRateSource :exec
DELETE FROM rate_sources
WHERE source_id = $1
`

func (q *Queries) DeleteRateSource(ctx context.Context, sourceID int32) error {
	_, err := q.db.ExecContext(ctx, deleteRateSource, sourceID)
	return err
}

const getAllRateSources = `-- name: GetAllRateSources :many
SELECT source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code FROM rate_sources
ORDER BY source_id
LIMIT $1
OFFSET $2
`

type GetAllRateSourcesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllRateSources(ctx context.Context, arg GetAllRateSourcesParams) ([]RateSource, error) {
	rows, err := q.db.QueryContext(ctx, getAllRateSources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateSource
	for rows.Next() {
		var i RateSource
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceName,
			&i.SourceLink,
			&i.SourceCountry,
			&i.SourceStatus,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRateSourceByCode = `-- name: GetRateSourceByCode :one
SELECT source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code FROM rate_sources
WHERE source_code = $1 LIMIT 1
`

func (q *Queries) GetRateSourceByCode(ctx context.Context, sourceCode sql.NullString) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, getRateSourceByCode, sourceCode)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}

const getRateSourceByID = `-- name: GetRateSourceByID :one
SELECT source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code FROM rate_sources
WHERE source_id = $1 LIMIT 1
`

func (q *Queries) GetRateSourceByID(ctx context.Context, sourceID int32) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, getRateSourceByID, sourceID)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}

const updateRateSource = `-- name: UpdateRateSource :one
UPDATE rate_sources
SET 
    source_name = COALESCE($2, source_name),
    source_link = COALESCE($3, source_link),
    source_country = COALESCE($4, source_country),
    source_status = COALESCE($5, source_status),
    source_code = COALESCE($6, source_code)
WHERE source_id = $1
RETURNING source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code
`

type UpdateRateSourceParams struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) UpdateRateSource(ctx context.Context, arg UpdateRateSourceParams) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, updateRateSource,
		arg.SourceID,
		arg.SourceName,
		arg.SourceLink,
		arg.SourceCountry,
		arg.SourceStatus,
		arg.SourceCode,
	)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}
