// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_source.sql

package db

import (
	"context"
	"database/sql"
)

const createRateSource = `-- name: CreateRateSource :one
INSERT INTO rate_sources (source_name, source_link, source_country, source_status, source_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code
`

type CreateRateSourceParams struct {
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) CreateRateSource(ctx context.Context, arg CreateRateSourceParams) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, createRateSource,
		arg.SourceName,
		arg.SourceLink,
		arg.SourceCountry,
		arg.SourceStatus,
		arg.SourceCode,
	)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}

const deleteRateSource = `-- name: DeleteRateSource :exec
DELETE FROM rate_sources
WHERE source_id = $1
`

func (q *Queries) DeleteRateSource(ctx context.Context, sourceID int32) error {
	_, err := q.db.ExecContext(ctx, deleteRateSource, sourceID)
	return err
}

const getRateSourceByCode = `-- name: GetRateSourceByCode :one
SELECT source_id, source_name, source_link, source_country, source_status, source_code FROM rate_sources
WHERE source_code = $1 LIMIT 1
`

type GetRateSourceByCodeRow struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) GetRateSourceByCode(ctx context.Context, sourceCode sql.NullString) (GetRateSourceByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getRateSourceByCode, sourceCode)
	var i GetRateSourceByCodeRow
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.SourceCode,
	)
	return i, err
}

const getRateSourceByID = `-- name: GetRateSourceByID :one
SELECT source_id, source_name, source_link, source_country, source_status, source_code FROM rate_sources
WHERE source_id = $1 LIMIT 1
`

type GetRateSourceByIDRow struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) GetRateSourceByID(ctx context.Context, sourceID int32) (GetRateSourceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRateSourceByID, sourceID)
	var i GetRateSourceByIDRow
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.SourceCode,
	)
	return i, err
}

const listRateSourceMetadata = `-- name: ListRateSourceMetadata :many
SELECT source_id, source_name, source_code, source_link FROM rate_sources
ORDER BY source_id
`

type ListRateSourceMetadataRow struct {
	SourceID   int32
	SourceName string
	SourceCode sql.NullString
	SourceLink sql.NullString
}

func (q *Queries) ListRateSourceMetadata(ctx context.Context) ([]ListRateSourceMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listRateSourceMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRateSourceMetadataRow
	for rows.Next() {
		var i ListRateSourceMetadataRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceName,
			&i.SourceCode,
			&i.SourceLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateSources = `-- name: ListRateSources :many
SELECT source_id, source_name, source_link, source_country, source_status, source_code FROM rate_sources
ORDER BY source_id
`

type ListRateSourcesRow struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) ListRateSources(ctx context.Context) ([]ListRateSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRateSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRateSourcesRow
	for rows.Next() {
		var i ListRateSourcesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceName,
			&i.SourceLink,
			&i.SourceCountry,
			&i.SourceStatus,
			&i.SourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateSource = `-- name: UpdateRateSource :one
UPDATE rate_sources
SET 
    source_name = COALESCE($2, source_name),
    source_link = COALESCE($3, source_link),
    source_country = COALESCE($4, source_country),
    source_status = COALESCE($5, source_status),
    source_code = COALESCE($6, source_code)
WHERE source_id = $1
RETURNING source_id, source_name, source_link, source_country, source_status, updated_at, created_at, source_code
`

type UpdateRateSourceParams struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	SourceCode    sql.NullString
}

func (q *Queries) UpdateRateSource(ctx context.Context, arg UpdateRateSourceParams) (RateSource, error) {
	row := q.db.QueryRowContext(ctx, updateRateSource,
		arg.SourceID,
		arg.SourceName,
		arg.SourceLink,
		arg.SourceCountry,
		arg.SourceStatus,
		arg.SourceCode,
	)
	var i RateSource
	err := row.Scan(
		&i.SourceID,
		&i.SourceName,
		&i.SourceLink,
		&i.SourceCountry,
		&i.SourceStatus,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SourceCode,
	)
	return i, err
}
