// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_source_fee_rule.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRateSourceFeeRule = `-- name: CreateRateSourceFeeRule :one
INSERT INTO rate_source_fee_rules (
    source_id,
    type_id,
    transaction_type,
    channel,
    fee_rate,
    fee_rate_min,
    fee_rate_max,
    fee_currency_id,
    fixed_fee,
    min_fee,
    max_fee,
    vat_rate,
    vat_applies,
    fee_includes_vat,
    swift_fee,
    swift_fee_currency_id,
    swift_fee_included,
    source_url,
    source_note,
    effective_from,
    effective_to
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included
`

type CreateRateSourceFeeRuleParams struct {
	SourceID           int32
	TypeID             int32
	TransactionType    string
	Channel            string
	FeeRate            sql.NullString
	FeeRateMin         sql.NullString
	FeeRateMax         sql.NullString
	FeeCurrencyID      sql.NullInt32
	FixedFee           sql.NullString
	MinFee             sql.NullString
	MaxFee             sql.NullString
	VatRate            string
	VatApplies         string
	FeeIncludesVat     bool
	SwiftFee           sql.NullString
	SwiftFeeCurrencyID sql.NullInt32
	SwiftFeeIncluded   bool
	SourceUrl          sql.NullString
	SourceNote         sql.NullString
	EffectiveFrom      time.Time
	EffectiveTo        sql.NullTime
}

func (q *Queries) CreateRateSourceFeeRule(ctx context.Context, arg CreateRateSourceFeeRuleParams) (RateSourceFeeRule, error) {
	row := q.db.QueryRowContext(ctx, createRateSourceFeeRule,
		arg.SourceID,
		arg.TypeID,
		arg.TransactionType,
		arg.Channel,
		arg.FeeRate,
		arg.FeeRateMin,
		arg.FeeRateMax,
		arg.FeeCurrencyID,
		arg.FixedFee,
		arg.MinFee,
		arg.MaxFee,
		arg.VatRate,
		arg.VatApplies,
		arg.FeeIncludesVat,
		arg.SwiftFee,
		arg.SwiftFeeCurrencyID,
		arg.SwiftFeeIncluded,
		arg.SourceUrl,
		arg.SourceNote,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i RateSourceFeeRule
	err := row.Scan(
		&i.FeeRuleID,
		&i.SourceID,
		&i.TypeID,
		&i.FeeRate,
		&i.VatRate,
		&i.VatApplies,
		&i.FeeIncludesVat,
		&i.SwiftFee,
		&i.SwiftFeeCurrencyID,
		&i.SourceUrl,
		&i.SourceNote,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TransactionType,
		&i.Channel,
		&i.FeeCurrencyID,
		&i.FixedFee,
		&i.MinFee,
		&i.MaxFee,
		&i.FeeRateMin,
		&i.FeeRateMax,
		&i.SwiftFeeIncluded,
	)
	return i, err
}

const deleteRateSourceFeeRule = `-- name: DeleteRateSourceFeeRule :exec
DELETE FROM rate_source_fee_rules
WHERE fee_rule_id = $1
`

func (q *Queries) DeleteRateSourceFeeRule(ctx context.Context, feeRuleID int32) error {
	_, err := q.db.ExecContext(ctx, deleteRateSourceFeeRule, feeRuleID)
	return err
}

const getActiveRateSourceFeeRule = `-- name: GetActiveRateSourceFeeRule :one
SELECT fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included FROM rate_source_fee_rules
WHERE source_id = $1
  AND type_id = $2
  AND transaction_type = $3
  AND channel = $4
  AND effective_from <= $5
  AND (effective_to IS NULL OR effective_to >= $5)
ORDER BY effective_from DESC, fee_rule_id DESC
LIMIT 1
`

type GetActiveRateSourceFeeRuleParams struct {
	SourceID        int32
	TypeID          int32
	TransactionType string
	Channel         string
	EffectiveFrom   time.Time
}

func (q *Queries) GetActiveRateSourceFeeRule(ctx context.Context, arg GetActiveRateSourceFeeRuleParams) (RateSourceFeeRule, error) {
	row := q.db.QueryRowContext(ctx, getActiveRateSourceFeeRule,
		arg.SourceID,
		arg.TypeID,
		arg.TransactionType,
		arg.Channel,
		arg.EffectiveFrom,
	)
	var i RateSourceFeeRule
	err := row.Scan(
		&i.FeeRuleID,
		&i.SourceID,
		&i.TypeID,
		&i.FeeRate,
		&i.VatRate,
		&i.VatApplies,
		&i.FeeIncludesVat,
		&i.SwiftFee,
		&i.SwiftFeeCurrencyID,
		&i.SourceUrl,
		&i.SourceNote,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TransactionType,
		&i.Channel,
		&i.FeeCurrencyID,
		&i.FixedFee,
		&i.MinFee,
		&i.MaxFee,
		&i.FeeRateMin,
		&i.FeeRateMax,
		&i.SwiftFeeIncluded,
	)
	return i, err
}

const getRateSourceFeeRuleByID = `-- name: GetRateSourceFeeRuleByID :one
SELECT fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included FROM rate_source_fee_rules
WHERE fee_rule_id = $1
LIMIT 1
`

func (q *Queries) GetRateSourceFeeRuleByID(ctx context.Context, feeRuleID int32) (RateSourceFeeRule, error) {
	row := q.db.QueryRowContext(ctx, getRateSourceFeeRuleByID, feeRuleID)
	var i RateSourceFeeRule
	err := row.Scan(
		&i.FeeRuleID,
		&i.SourceID,
		&i.TypeID,
		&i.FeeRate,
		&i.VatRate,
		&i.VatApplies,
		&i.FeeIncludesVat,
		&i.SwiftFee,
		&i.SwiftFeeCurrencyID,
		&i.SourceUrl,
		&i.SourceNote,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TransactionType,
		&i.Channel,
		&i.FeeCurrencyID,
		&i.FixedFee,
		&i.MinFee,
		&i.MaxFee,
		&i.FeeRateMin,
		&i.FeeRateMax,
		&i.SwiftFeeIncluded,
	)
	return i, err
}

const listActiveRateSourceFeeRulesBySource = `-- name: ListActiveRateSourceFeeRulesBySource :many
SELECT fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included FROM rate_source_fee_rules
WHERE source_id = $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
ORDER BY type_id, transaction_type, channel, effective_from DESC, fee_rule_id DESC
`

type ListActiveRateSourceFeeRulesBySourceParams struct {
	SourceID      int32
	EffectiveFrom time.Time
}

func (q *Queries) ListActiveRateSourceFeeRulesBySource(ctx context.Context, arg ListActiveRateSourceFeeRulesBySourceParams) ([]RateSourceFeeRule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRateSourceFeeRulesBySource, arg.SourceID, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateSourceFeeRule
	for rows.Next() {
		var i RateSourceFeeRule
		if err := rows.Scan(
			&i.FeeRuleID,
			&i.SourceID,
			&i.TypeID,
			&i.FeeRate,
			&i.VatRate,
			&i.VatApplies,
			&i.FeeIncludesVat,
			&i.SwiftFee,
			&i.SwiftFeeCurrencyID,
			&i.SourceUrl,
			&i.SourceNote,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TransactionType,
			&i.Channel,
			&i.FeeCurrencyID,
			&i.FixedFee,
			&i.MinFee,
			&i.MaxFee,
			&i.FeeRateMin,
			&i.FeeRateMax,
			&i.SwiftFeeIncluded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateSourceFeeRules = `-- name: ListRateSourceFeeRules :many
SELECT fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included FROM rate_source_fee_rules
ORDER BY source_id, type_id, transaction_type, channel, effective_from DESC, fee_rule_id DESC
`

func (q *Queries) ListRateSourceFeeRules(ctx context.Context) ([]RateSourceFeeRule, error) {
	rows, err := q.db.QueryContext(ctx, listRateSourceFeeRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateSourceFeeRule
	for rows.Next() {
		var i RateSourceFeeRule
		if err := rows.Scan(
			&i.FeeRuleID,
			&i.SourceID,
			&i.TypeID,
			&i.FeeRate,
			&i.VatRate,
			&i.VatApplies,
			&i.FeeIncludesVat,
			&i.SwiftFee,
			&i.SwiftFeeCurrencyID,
			&i.SourceUrl,
			&i.SourceNote,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TransactionType,
			&i.Channel,
			&i.FeeCurrencyID,
			&i.FixedFee,
			&i.MinFee,
			&i.MaxFee,
			&i.FeeRateMin,
			&i.FeeRateMax,
			&i.SwiftFeeIncluded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateSourceFeeRulesBySource = `-- name: ListRateSourceFeeRulesBySource :many
SELECT fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included FROM rate_source_fee_rules
WHERE source_id = $1
ORDER BY type_id, transaction_type, channel, effective_from DESC, fee_rule_id DESC
`

func (q *Queries) ListRateSourceFeeRulesBySource(ctx context.Context, sourceID int32) ([]RateSourceFeeRule, error) {
	rows, err := q.db.QueryContext(ctx, listRateSourceFeeRulesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateSourceFeeRule
	for rows.Next() {
		var i RateSourceFeeRule
		if err := rows.Scan(
			&i.FeeRuleID,
			&i.SourceID,
			&i.TypeID,
			&i.FeeRate,
			&i.VatRate,
			&i.VatApplies,
			&i.FeeIncludesVat,
			&i.SwiftFee,
			&i.SwiftFeeCurrencyID,
			&i.SourceUrl,
			&i.SourceNote,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TransactionType,
			&i.Channel,
			&i.FeeCurrencyID,
			&i.FixedFee,
			&i.MinFee,
			&i.MaxFee,
			&i.FeeRateMin,
			&i.FeeRateMax,
			&i.SwiftFeeIncluded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateSourceFeeRule = `-- name: UpdateRateSourceFeeRule :one
UPDATE rate_source_fee_rules
SET
    source_id = COALESCE($1, source_id),
    type_id = COALESCE($2, type_id),
    transaction_type = COALESCE($3, transaction_type),
    channel = COALESCE($4, channel),
    fee_rate = COALESCE($5, fee_rate),
    fee_rate_min = COALESCE($6, fee_rate_min),
    fee_rate_max = COALESCE($7, fee_rate_max),
    fee_currency_id = COALESCE($8, fee_currency_id),
    fixed_fee = COALESCE($9, fixed_fee),
    min_fee = COALESCE($10, min_fee),
    max_fee = COALESCE($11, max_fee),
    vat_rate = COALESCE($12, vat_rate),
    vat_applies = COALESCE($13, vat_applies),
    fee_includes_vat = COALESCE($14, fee_includes_vat),
    swift_fee = COALESCE($15, swift_fee),
    swift_fee_currency_id = COALESCE($16, swift_fee_currency_id),
    swift_fee_included = COALESCE($17, swift_fee_included),
    source_url = COALESCE($18, source_url),
    source_note = COALESCE($19, source_note),
    effective_from = COALESCE($20, effective_from),
    effective_to = COALESCE($21, effective_to),
    updated_at = CURRENT_TIMESTAMP
WHERE fee_rule_id = $22
RETURNING fee_rule_id, source_id, type_id, fee_rate, vat_rate, vat_applies, fee_includes_vat, swift_fee, swift_fee_currency_id, source_url, source_note, effective_from, effective_to, updated_at, created_at, transaction_type, channel, fee_currency_id, fixed_fee, min_fee, max_fee, fee_rate_min, fee_rate_max, swift_fee_included
`

type UpdateRateSourceFeeRuleParams struct {
	SourceID           sql.NullInt32
	TypeID             sql.NullInt32
	TransactionType    sql.NullString
	Channel            sql.NullString
	FeeRate            sql.NullString
	FeeRateMin         sql.NullString
	FeeRateMax         sql.NullString
	FeeCurrencyID      sql.NullInt32
	FixedFee           sql.NullString
	MinFee             sql.NullString
	MaxFee             sql.NullString
	VatRate            sql.NullString
	VatApplies         sql.NullString
	FeeIncludesVat     sql.NullBool
	SwiftFee           sql.NullString
	SwiftFeeCurrencyID sql.NullInt32
	SwiftFeeIncluded   sql.NullBool
	SourceUrl          sql.NullString
	SourceNote         sql.NullString
	EffectiveFrom      sql.NullTime
	EffectiveTo        sql.NullTime
	FeeRuleID          int32
}

func (q *Queries) UpdateRateSourceFeeRule(ctx context.Context, arg UpdateRateSourceFeeRuleParams) (RateSourceFeeRule, error) {
	row := q.db.QueryRowContext(ctx, updateRateSourceFeeRule,
		arg.SourceID,
		arg.TypeID,
		arg.TransactionType,
		arg.Channel,
		arg.FeeRate,
		arg.FeeRateMin,
		arg.FeeRateMax,
		arg.FeeCurrencyID,
		arg.FixedFee,
		arg.MinFee,
		arg.MaxFee,
		arg.VatRate,
		arg.VatApplies,
		arg.FeeIncludesVat,
		arg.SwiftFee,
		arg.SwiftFeeCurrencyID,
		arg.SwiftFeeIncluded,
		arg.SourceUrl,
		arg.SourceNote,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.FeeRuleID,
	)
	var i RateSourceFeeRule
	err := row.Scan(
		&i.FeeRuleID,
		&i.SourceID,
		&i.TypeID,
		&i.FeeRate,
		&i.VatRate,
		&i.VatApplies,
		&i.FeeIncludesVat,
		&i.SwiftFee,
		&i.SwiftFeeCurrencyID,
		&i.SourceUrl,
		&i.SourceNote,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TransactionType,
		&i.Channel,
		&i.FeeCurrencyID,
		&i.FixedFee,
		&i.MinFee,
		&i.MaxFee,
		&i.FeeRateMin,
		&i.FeeRateMax,
		&i.SwiftFeeIncluded,
	)
	return i, err
}
