// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password,
    user_type,
    email_verified,
    time_zone,
    language_preference,
    country_of_residence,
    country_of_birth,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username           string
	Email              string
	Password           string
	UserType           sql.NullString
	EmailVerified      sql.NullBool
	TimeZone           sql.NullString
	LanguagePreference sql.NullString
	CountryOfResidence sql.NullString
	CountryOfBirth     sql.NullString
	IsActive           sql.NullBool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.UserType,
		arg.EmailVerified,
		arg.TimeZone,
		arg.LanguagePreference,
		arg.CountryOfResidence,
		arg.CountryOfBirth,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, email)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at FROM users
ORDER BY created_at 
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.UserType,
			&i.EmailVerified,
			&i.TimeZone,
			&i.LanguagePreference,
			&i.CountryOfResidence,
			&i.CountryOfBirth,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    email = COALESCE($2, email),
    password = COALESCE($3, password),
    user_type = COALESCE($4, user_type),
    email_verified = COALESCE($5, email_verified),
    time_zone = COALESCE($6, time_zone),
    language_preference = COALESCE($7, language_preference),
    country_of_residence = COALESCE($8, country_of_residence),
    country_of_birth = COALESCE($9, country_of_birth),
    is_active = COALESCE($10, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $11
RETURNING user_id, username, email, password, user_type, email_verified, time_zone, language_preference, country_of_residence, country_of_birth, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	Username           sql.NullString
	Email              sql.NullString
	Password           sql.NullString
	UserType           sql.NullString
	EmailVerified      sql.NullBool
	TimeZone           sql.NullString
	LanguagePreference sql.NullString
	CountryOfResidence sql.NullString
	CountryOfBirth     sql.NullString
	IsActive           sql.NullBool
	UserID             int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.UserType,
		arg.EmailVerified,
		arg.TimeZone,
		arg.LanguagePreference,
		arg.CountryOfResidence,
		arg.CountryOfBirth,
		arg.IsActive,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
