// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
    user_id,
    email,
    secret_code_hash
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    user_id,
    email,
    secret_code_hash,
    is_used,
    created_at,
    expired_at
`

type CreateVerifyEmailParams struct {
	UserID         int32
	Email          string
	SecretCodeHash string
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerifyEmail, arg.UserID, arg.Email, arg.SecretCodeHash)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.SecretCodeHash,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getVerifyEmail = `-- name: GetVerifyEmail :one
SELECT
    id,
    user_id,
    email,
    secret_code_hash,
    is_used,
    created_at,
    expired_at
FROM verify_emails
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVerifyEmail(ctx context.Context, id int64) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, getVerifyEmail, id)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.SecretCodeHash,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :one
UPDATE users
SET
    email_verified = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    user_id = $1
RETURNING
    user_id,
    username,
    email,
    password,
    user_type,
    email_verified,
    time_zone,
    language_preference,
    country_of_residence,
    country_of_birth,
    is_active,
    created_at,
    updated_at,
    first_name,
    last_name
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmailVerified, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.EmailVerified,
		&i.TimeZone,
		&i.LanguagePreference,
		&i.CountryOfResidence,
		&i.CountryOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateVerifyEmail = `-- name: UpdateVerifyEmail :one
UPDATE verify_emails
SET
    is_used = TRUE
WHERE
    id = $1
    AND user_id = $2
    AND secret_code_hash = $3
    AND is_used = FALSE
    AND expired_at > now()
RETURNING
    id,
    user_id,
    email,
    secret_code_hash,
    is_used,
    created_at,
    expired_at
`

type UpdateVerifyEmailParams struct {
	ID             int64
	UserID         int32
	SecretCodeHash string
}

func (q *Queries) UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, updateVerifyEmail, arg.ID, arg.UserID, arg.SecretCodeHash)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.SecretCodeHash,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
