// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package db

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (country_name, currency_id)
VALUES ($1, $2)
RETURNING country_id, country_name, currency_id, updated_at, created_at
`

type CreateCountryParams struct {
	CountryName string
	CurrencyID  int32
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, arg.CountryName, arg.CurrencyID)
	var i Country
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE country_id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, countryID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCountry, countryID)
	return err
}

const getAllCountries = `-- name: GetAllCountries :many
SELECT country_id, country_name, currency_id, updated_at, created_at FROM countries
ORDER BY country_id
LIMIT $1
OFFSET $2
`

type GetAllCountriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllCountries(ctx context.Context, arg GetAllCountriesParams) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getAllCountries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.CountryID,
			&i.CountryName,
			&i.CurrencyID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountriesByCurrencyID = `-- name: GetCountriesByCurrencyID :many
SELECT country_id, country_name, currency_id, updated_at, created_at FROM countries
WHERE currency_id = $1
ORDER BY country_id
`

func (q *Queries) GetCountriesByCurrencyID(ctx context.Context, currencyID int32) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountriesByCurrencyID, currencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.CountryID,
			&i.CountryName,
			&i.CurrencyID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT country_id, country_name, currency_id, updated_at, created_at FROM countries 
WHERE country_id = $1 LIMIT 1
`

func (q *Queries) GetCountryByID(ctx context.Context, countryID int32) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByID, countryID)
	var i Country
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET country_name = $2, currency_id = $3, updated_at = CURRENT_TIMESTAMP
WHERE country_id = $1
RETURNING country_id, country_name, currency_id, updated_at, created_at
`

type UpdateCountryParams struct {
	CountryID   int32
	CountryName string
	CurrencyID  int32
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, updateCountry, arg.CountryID, arg.CountryName, arg.CurrencyID)
	var i Country
	err := row.Scan(
		&i.CountryID,
		&i.CountryName,
		&i.CurrencyID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
