// Package db contains database-related code and tests generated by sqlc
package db

import (
	"context"
	"database/sql"
	"testing"

	"github.com/ThanhVinhTong/rate-pulse/util"
	"github.com/stretchr/testify/require"
)

// TestCreateCurrency tests the CreateCurrency database operation.
// This test verifies that:
// - A new currency can be successfully created in the database
// - All provided fields are correctly stored and returned
// - Auto-generated fields (ID, timestamps) are properly set
// - Null-able fields are handled correctly
func TestCreateCurrency(t *testing.T) {
	// Prepare test data for creating a Vietnamese Dong currency
	// Using real currency data makes the test more meaningful
	currencies := util.GetAllCurrencies()
	for _, currency := range currencies {
		arg := CreateCurrencyParams{
			CurrencyCode:    currency["currency_code"].(string),
			CurrencyName:    currency["currency_name"].(string),
			CurrencyCountry: sql.NullString{String: currency["currency_country"].(string), Valid: true},
			CurrencySymbol:  sql.NullString{String: currency["currency_symbol"].(string), Valid: true},
		}

		// Execute the CreateCurrency query using the test database connection
		currency, err := testQueries.CreateCurrency(context.Background(), arg)

		// Assert that no error occurred during the database operation
		require.NoError(t, err)

		// Assert that the returned currency object is not empty
		require.NotEmpty(t, currency)

		// Verify that all input fields were correctly stored and returned
		require.Equal(t, arg.CurrencyCode, currency.CurrencyCode)
		require.Equal(t, arg.CurrencyName, currency.CurrencyName)
		require.Equal(t, arg.CurrencyCountry, currency.CurrencyCountry)
		require.Equal(t, arg.CurrencySymbol, currency.CurrencySymbol)

		// Verify that auto-generated fields are properly set by the database
		// CurrencyID should be a non-zero value (auto-incremented primary key)
		require.NotZero(t, currency.CurrencyID)

		// UpdatedAt and CreatedAt timestamps should be set by database triggers/defaults
		require.NotZero(t, currency.UpdatedAt)
		require.NotZero(t, currency.CreatedAt)
	}
}

func TestGetCurrencyByID(t *testing.T) {
	// Use the first currency that was created in TestCreateCurrency (should have ID 1)
	currencyID := int32(1)
	currencyFromDB, err := testQueries.GetCurrencyByID(context.Background(), currencyID)

	require.NoError(t, err)
	require.NotEmpty(t, currencyFromDB)

	// Verify it has the expected USD data (first currency in our list)
	require.Equal(t, "USD", currencyFromDB.CurrencyCode)
	require.Equal(t, "United States Dollar", currencyFromDB.CurrencyName)
	require.Equal(t, "United States", currencyFromDB.CurrencyCountry.String)
	require.Equal(t, "$", currencyFromDB.CurrencySymbol.String)

	// Verify auto-generated fields are set
	require.NotZero(t, currencyFromDB.CurrencyID)
	require.NotZero(t, currencyFromDB.UpdatedAt)
	require.NotZero(t, currencyFromDB.CreatedAt)
}

func TestGetAllCurrencies(t *testing.T) {
	currencies, err := testQueries.GetAllCurrencies(context.Background(), GetAllCurrenciesParams{
		Limit:  10,
		Offset: 0,
	})
	require.NoError(t, err)
	require.NotEmpty(t, currencies)
	require.Equal(t, util.GetLengthListCurrencies(), len(currencies))
}

func TestUpdateCurrency(t *testing.T) {
	currencyID := int32(1)

	arg := UpdateCurrencyParams{
		CurrencyID:      currencyID,
		CurrencyCode:    "USD",
		CurrencyName:    "United States Dollar",
		CurrencyCountry: sql.NullString{String: "United States of America", Valid: true},
		CurrencySymbol:  sql.NullString{String: "$", Valid: true},
	}

	currency, err := testQueries.UpdateCurrency(context.Background(), arg)
	require.NoError(t, err)
	require.NotEmpty(t, currency)
	require.Equal(t, arg.CurrencyCode, currency.CurrencyCode)
	require.Equal(t, arg.CurrencyName, currency.CurrencyName)
}

func TestDeleteCurrency(t *testing.T) {
	// Use the last seeded currency ID
	currencyID := int32(util.GetLengthListCurrencies())

	// Delete the currency
	err := testQueries.DeleteCurrency(context.Background(), currencyID)
	require.NoError(t, err)

	// Verify it was deleted
	currency, err := testQueries.GetCurrencyByID(context.Background(), currencyID)
	require.Error(t, err)
	require.Empty(t, currency)

	// Re-insert the deleted currency so other tests still see the full dataset
	currencies := util.GetAllCurrencies()
	deletedCurrency := currencies[len(currencies)-1]

	_, err = testDB.ExecContext(
		context.Background(),
		`INSERT INTO currencies (currency_id, currency_code, currency_name, currency_country, currency_symbol)
         VALUES ($1, $2, $3, $4, $5)`,
		currencyID,
		deletedCurrency["currency_code"].(string),
		deletedCurrency["currency_name"].(string),
		deletedCurrency["currency_country"].(string),
		deletedCurrency["currency_symbol"].(string),
	)
	require.NoError(t, err)
}
