// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency.sql

package db

import (
	"context"
	"database/sql"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (currency_code, currency_name, currency_symbol)
VALUES ($1, $2, $3)
RETURNING currency_id, currency_code, currency_name, currency_symbol, updated_at, created_at
`

type CreateCurrencyParams struct {
	CurrencyCode   string
	CurrencyName   string
	CurrencySymbol sql.NullString
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrency, arg.CurrencyCode, arg.CurrencyName, arg.CurrencySymbol)
	var i Currency
	err := row.Scan(
		&i.CurrencyID,
		&i.CurrencyCode,
		&i.CurrencyName,
		&i.CurrencySymbol,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currencies
WHERE currency_id = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, currencyID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, currencyID)
	return err
}

const getAllCurrencies = `-- name: GetAllCurrencies :many
SELECT currency_id, currency_code, currency_name, currency_symbol, updated_at, created_at FROM currencies
ORDER BY currency_id
LIMIT $1
OFFSET $2
`

type GetAllCurrenciesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllCurrencies(ctx context.Context, arg GetAllCurrenciesParams) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, getAllCurrencies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.CurrencyID,
			&i.CurrencyCode,
			&i.CurrencyName,
			&i.CurrencySymbol,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT currency_id, currency_code, currency_name, currency_symbol, updated_at, created_at FROM currencies 
WHERE currency_code = $1 LIMIT 1
`

func (q *Queries) GetCurrencyByCode(ctx context.Context, currencyCode string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, currencyCode)
	var i Currency
	err := row.Scan(
		&i.CurrencyID,
		&i.CurrencyCode,
		&i.CurrencyName,
		&i.CurrencySymbol,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT currency_id, currency_code, currency_name, currency_symbol, updated_at, created_at FROM currencies 
WHERE currency_id = $1 LIMIT 1
`

func (q *Queries) GetCurrencyByID(ctx context.Context, currencyID int32) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByID, currencyID)
	var i Currency
	err := row.Scan(
		&i.CurrencyID,
		&i.CurrencyCode,
		&i.CurrencyName,
		&i.CurrencySymbol,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCurrency = `-- name: UpdateCurrency :one
UPDATE currencies
SET currency_code = $2, currency_name = $3, currency_symbol = $4, updated_at = CURRENT_TIMESTAMP
WHERE currency_id = $1
RETURNING currency_id, currency_code, currency_name, currency_symbol, updated_at, created_at
`

type UpdateCurrencyParams struct {
	CurrencyID     int32
	CurrencyCode   string
	CurrencyName   string
	CurrencySymbol sql.NullString
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, updateCurrency,
		arg.CurrencyID,
		arg.CurrencyCode,
		arg.CurrencyName,
		arg.CurrencySymbol,
	)
	var i Currency
	err := row.Scan(
		&i.CurrencyID,
		&i.CurrencyCode,
		&i.CurrencyName,
		&i.CurrencySymbol,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
