// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Currency struct {
	CurrencyID      int32
	CurrencyCode    string
	CurrencyName    string
	CurrencyCountry sql.NullString
	CurrencySymbol  sql.NullString
	UpdatedAt       sql.NullTime
	CreatedAt       sql.NullTime
}

type ExchangeRate struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	UpdatedAt             sql.NullTime
	CreatedAt             sql.NullTime
}

type RateSource struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	UpdatedAt     sql.NullTime
	CreatedAt     sql.NullTime
}

type User struct {
	UserID             int32
	Username           string
	Email              string
	Password           string
	UserType           sql.NullString
	EmailVerified      sql.NullBool
	TimeZone           sql.NullString
	LanguagePreference sql.NullString
	CountryOfResidence sql.NullString
	CountryOfBirth     sql.NullString
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type UserCurrencyPreference struct {
	CurrencyID   int32
	UserID       int32
	IsFavorite   sql.NullBool
	DisplayOrder sql.NullInt32
	UpdatedAt    sql.NullTime
	CreatedAt    sql.NullTime
}

type UserRateSourcePreference struct {
	SourceID  int32
	UserID    int32
	IsPrimary sql.NullBool
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}
