// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Currency struct {
	CurrencyID      int32
	CurrencyCode    string
	CurrencyName    string
	CurrencyCountry sql.NullString
	CurrencySymbol  sql.NullString
	UpdatedAt       sql.NullTime
	CreatedAt       sql.NullTime
}

type ExchangeRate struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	UpdatedAt             sql.NullTime
	CreatedAt             sql.NullTime
}

type RateSource struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	UpdatedAt     sql.NullTime
	CreatedAt     sql.NullTime
}
