// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Country struct {
	CountryID   int32
	CountryName string
	CurrencyID  int32
	UpdatedAt   sql.NullTime
	CreatedAt   sql.NullTime
}

type Currency struct {
	CurrencyID     int32
	CurrencyCode   string
	CurrencyName   string
	CurrencySymbol sql.NullString
	UpdatedAt      sql.NullTime
	CreatedAt      sql.NullTime
}

type ExchangeRate struct {
	RateID                int32
	RateValue             string
	SourceCurrencyID      int32
	DestinationCurrencyID int32
	ValidFromDate         time.Time
	ValidToDate           sql.NullTime
	SourceID              sql.NullInt32
	UpdatedAt             sql.NullTime
	CreatedAt             sql.NullTime
	Type                  int32
}

type Payment struct {
	PaymentID      int32
	UserID         int32
	SubscriptionID sql.NullInt32
	TransactionID  sql.NullString
	Amount         string
	Currency       string
	PaymentMethod  sql.NullString
	PaymentStatus  sql.NullString
	PaymentDate    sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type RateSource struct {
	SourceID      int32
	SourceName    string
	SourceLink    sql.NullString
	SourceCountry sql.NullString
	SourceStatus  sql.NullString
	UpdatedAt     sql.NullTime
	CreatedAt     sql.NullTime
}

type SubscriptionPlan struct {
	PlanID          int32
	PlanName        string
	PlanPrice       string
	HistoricalDays  int32
	RateLimitPerDay int32
	Features        sql.NullString
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	UserID             int32
	Username           string
	Email              string
	Password           string
	UserType           sql.NullString
	EmailVerified      sql.NullBool
	TimeZone           sql.NullString
	LanguagePreference sql.NullString
	CountryOfResidence sql.NullString
	CountryOfBirth     sql.NullString
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type UserCurrencyPreference struct {
	CurrencyID   int32
	UserID       int32
	IsFavorite   sql.NullBool
	DisplayOrder sql.NullInt32
	UpdatedAt    sql.NullTime
	CreatedAt    sql.NullTime
}

type UserRateSourcePreference struct {
	SourceID  int32
	UserID    int32
	IsPrimary sql.NullBool
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}

type UserSubscription struct {
	SubscriptionID int32
	UserID         int32
	PlanID         int32
	Status         sql.NullString
	StartDate      time.Time
	EndDate        sql.NullTime
	AutoRenew      sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
