// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    user_id,
    subscription_id,
    transaction_id,
    amount,
    currency,
    payment_method,
    payment_status,
    payment_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID         int32
	SubscriptionID sql.NullInt32
	TransactionID  sql.NullString
	Amount         string
	Currency       string
	PaymentMethod  sql.NullString
	PaymentStatus  sql.NullString
	PaymentDate    sql.NullTime
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.UserID,
		arg.SubscriptionID,
		arg.TransactionID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.PaymentDate,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.SubscriptionID,
		&i.TransactionID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments
WHERE payment_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, paymentID int32) error {
	_, err := q.db.ExecContext(ctx, deletePayment, paymentID)
	return err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at FROM payments
ORDER BY payment_date DESC
`

func (q *Queries) GetAllPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.SubscriptionID,
			&i.TransactionID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at FROM payments
WHERE payment_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, paymentID int32) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, paymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.SubscriptionID,
		&i.TransactionID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByTransactionID = `-- name: GetPaymentByTransactionID :one
SELECT payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at FROM payments
WHERE transaction_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByTransactionID(ctx context.Context, transactionID sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByTransactionID, transactionID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.SubscriptionID,
		&i.TransactionID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentsByStatus = `-- name: GetPaymentsByStatus :many
SELECT payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at FROM payments
WHERE payment_status = $1
ORDER BY payment_date DESC
`

func (q *Queries) GetPaymentsByStatus(ctx context.Context, paymentStatus sql.NullString) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByStatus, paymentStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.SubscriptionID,
			&i.TransactionID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByUserID = `-- name: GetPaymentsByUserID :many
SELECT payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at FROM payments
WHERE user_id = $1
ORDER BY payment_date DESC
`

func (q *Queries) GetPaymentsByUserID(ctx context.Context, userID int32) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.SubscriptionID,
			&i.TransactionID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET
    subscription_id = COALESCE($1, subscription_id),
    transaction_id = COALESCE($2, transaction_id),
    amount = COALESCE($3, amount),
    currency = COALESCE($4, currency),
    payment_method = COALESCE($5, payment_method),
    payment_status = COALESCE($6, payment_status),
    payment_date = COALESCE($7, payment_date),
    updated_at = CURRENT_TIMESTAMP
WHERE payment_id = $8
RETURNING payment_id, user_id, subscription_id, transaction_id, amount, currency, payment_method, payment_status, payment_date, created_at, updated_at
`

type UpdatePaymentParams struct {
	SubscriptionID sql.NullInt32
	TransactionID  sql.NullString
	Amount         sql.NullString
	Currency       sql.NullString
	PaymentMethod  sql.NullString
	PaymentStatus  sql.NullString
	PaymentDate    sql.NullTime
	PaymentID      int32
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment,
		arg.SubscriptionID,
		arg.TransactionID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.PaymentDate,
		arg.PaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.SubscriptionID,
		&i.TransactionID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
