// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_subscription.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO user_subscriptions (
    user_id,
    plan_id,
    status,
    start_date,
    end_date,
    auto_renew
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at
`

type CreateUserSubscriptionParams struct {
	UserID    int32
	PlanID    int32
	Status    sql.NullString
	StartDate time.Time
	EndDate   sql.NullTime
	AutoRenew sql.NullBool
}

func (q *Queries) CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, createUserSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.AutoRenew,
	)
	var i UserSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSubscription = `-- name: DeleteUserSubscription :exec
DELETE FROM user_subscriptions
WHERE subscription_id = $1
`

func (q *Queries) DeleteUserSubscription(ctx context.Context, subscriptionID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubscription, subscriptionID)
	return err
}

const getActiveUserSubscriptionByUserID = `-- name: GetActiveUserSubscriptionByUserID :one
SELECT subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at FROM user_subscriptions
WHERE user_id = $1 AND status = 'active'
ORDER BY start_date DESC
LIMIT 1
`

func (q *Queries) GetActiveUserSubscriptionByUserID(ctx context.Context, userID int32) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserSubscriptionByUserID, userID)
	var i UserSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUserSubscriptions = `-- name: GetAllUserSubscriptions :many
SELECT subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at FROM user_subscriptions
ORDER BY start_date DESC
`

func (q *Queries) GetAllUserSubscriptions(ctx context.Context) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscriptionByID = `-- name: GetUserSubscriptionByID :one
SELECT subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at FROM user_subscriptions
WHERE subscription_id = $1 LIMIT 1
`

func (q *Queries) GetUserSubscriptionByID(ctx context.Context, subscriptionID int32) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscriptionByID, subscriptionID)
	var i UserSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptionsByStatus = `-- name: GetUserSubscriptionsByStatus :many
SELECT subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at FROM user_subscriptions
WHERE status = $1
ORDER BY start_date DESC
`

func (q *Queries) GetUserSubscriptionsByStatus(ctx context.Context, status sql.NullString) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscriptionsByUserID = `-- name: GetUserSubscriptionsByUserID :many
SELECT subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at FROM user_subscriptions
WHERE user_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetUserSubscriptionsByUserID(ctx context.Context, userID int32) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE user_subscriptions
SET
    plan_id = COALESCE($1, plan_id),
    status = COALESCE($2, status),
    start_date = COALESCE($3, start_date),
    end_date = COALESCE($4, end_date),
    auto_renew = COALESCE($5, auto_renew),
    updated_at = CURRENT_TIMESTAMP
WHERE subscription_id = $6
RETURNING subscription_id, user_id, plan_id, status, start_date, end_date, auto_renew, created_at, updated_at
`

type UpdateUserSubscriptionParams struct {
	PlanID         sql.NullInt32
	Status         sql.NullString
	StartDate      sql.NullTime
	EndDate        sql.NullTime
	AutoRenew      sql.NullBool
	SubscriptionID int32
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, updateUserSubscription,
		arg.PlanID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.AutoRenew,
		arg.SubscriptionID,
	)
	var i UserSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
