// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_rate_source_preference.sql

package db

import (
	"context"
	"database/sql"
)

const createRateSourcePreference = `-- name: CreateRateSourcePreference :one
INSERT INTO user_rate_source_preferences (
    source_id,
    user_id,
    is_primary
) VALUES (
    $1, $2, $3
) RETURNING source_id, user_id, is_primary, updated_at, created_at
`

type CreateRateSourcePreferenceParams struct {
	SourceID  int32
	UserID    int32
	IsPrimary sql.NullBool
}

func (q *Queries) CreateRateSourcePreference(ctx context.Context, arg CreateRateSourcePreferenceParams) (UserRateSourcePreference, error) {
	row := q.db.QueryRowContext(ctx, createRateSourcePreference, arg.SourceID, arg.UserID, arg.IsPrimary)
	var i UserRateSourcePreference
	err := row.Scan(
		&i.SourceID,
		&i.UserID,
		&i.IsPrimary,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRateSourcePreference = `-- name: DeleteRateSourcePreference :exec
DELETE FROM user_rate_source_preferences
WHERE source_id = $1 AND user_id = $2
`

type DeleteRateSourcePreferenceParams struct {
	SourceID int32
	UserID   int32
}

func (q *Queries) DeleteRateSourcePreference(ctx context.Context, arg DeleteRateSourcePreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteRateSourcePreference, arg.SourceID, arg.UserID)
	return err
}

const getAllRateSourcePreferences = `-- name: GetAllRateSourcePreferences :many
SELECT source_id, user_id, is_primary, updated_at, created_at FROM user_rate_source_preferences
ORDER BY user_id, is_primary DESC
LIMIT $1 OFFSET $2
`

type GetAllRateSourcePreferencesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllRateSourcePreferences(ctx context.Context, arg GetAllRateSourcePreferencesParams) ([]UserRateSourcePreference, error) {
	rows, err := q.db.QueryContext(ctx, getAllRateSourcePreferences, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRateSourcePreference
	for rows.Next() {
		var i UserRateSourcePreference
		if err := rows.Scan(
			&i.SourceID,
			&i.UserID,
			&i.IsPrimary,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRateSourcePreferencesBySourceID = `-- name: GetRateSourcePreferencesBySourceID :many
SELECT ursp.source_id, ursp.user_id, ursp.is_primary, ursp.updated_at, ursp.created_at 
FROM user_rate_source_preferences ursp
INNER JOIN users u ON ursp.user_id = u.user_id
WHERE u.email = $1
ORDER BY ursp.is_primary DESC, ursp.created_at ASC
LIMIT $2 OFFSET $3
`

type GetRateSourcePreferencesBySourceIDParams struct {
	Email  string
	Limit  int32
	Offset int32
}

func (q *Queries) GetRateSourcePreferencesBySourceID(ctx context.Context, arg GetRateSourcePreferencesBySourceIDParams) ([]UserRateSourcePreference, error) {
	rows, err := q.db.QueryContext(ctx, getRateSourcePreferencesBySourceID, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRateSourcePreference
	for rows.Next() {
		var i UserRateSourcePreference
		if err := rows.Scan(
			&i.SourceID,
			&i.UserID,
			&i.IsPrimary,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRateSourcePreferencesByUserID = `-- name: GetRateSourcePreferencesByUserID :many
SELECT source_id, user_id, is_primary, updated_at, created_at FROM user_rate_source_preferences
WHERE user_id = $1
ORDER BY is_primary DESC, created_at ASC
LIMIT $2 OFFSET $3
`

type GetRateSourcePreferencesByUserIDParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

func (q *Queries) GetRateSourcePreferencesByUserID(ctx context.Context, arg GetRateSourcePreferencesByUserIDParams) ([]UserRateSourcePreference, error) {
	rows, err := q.db.QueryContext(ctx, getRateSourcePreferencesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRateSourcePreference
	for rows.Next() {
		var i UserRateSourcePreference
		if err := rows.Scan(
			&i.SourceID,
			&i.UserID,
			&i.IsPrimary,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateSourcePreference = `-- name: UpdateRateSourcePreference :one
UPDATE user_rate_source_preferences
SET
    is_primary = COALESCE($1, is_primary),
    updated_at = CURRENT_TIMESTAMP
WHERE source_id = $2 AND user_id = $3
RETURNING source_id, user_id, is_primary, updated_at, created_at
`

type UpdateRateSourcePreferenceParams struct {
	IsPrimary sql.NullBool
	SourceID  int32
	UserID    int32
}

func (q *Queries) UpdateRateSourcePreference(ctx context.Context, arg UpdateRateSourcePreferenceParams) (UserRateSourcePreference, error) {
	row := q.db.QueryRowContext(ctx, updateRateSourcePreference, arg.IsPrimary, arg.SourceID, arg.UserID)
	var i UserRateSourcePreference
	err := row.Scan(
		&i.SourceID,
		&i.UserID,
		&i.IsPrimary,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
