// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_currency_preference.sql

package db

import (
	"context"
	"database/sql"
)

const createCurrencyPreference = `-- name: CreateCurrencyPreference :one
INSERT INTO user_currency_preferences (
    currency_id,
    user_id,
    is_favorite,
    display_order
) VALUES (
    $1, $2, $3, $4
) RETURNING currency_id, user_id, is_favorite, display_order, updated_at, created_at
`

type CreateCurrencyPreferenceParams struct {
	CurrencyID   int32
	UserID       int32
	IsFavorite   sql.NullBool
	DisplayOrder sql.NullInt32
}

func (q *Queries) CreateCurrencyPreference(ctx context.Context, arg CreateCurrencyPreferenceParams) (UserCurrencyPreference, error) {
	row := q.db.QueryRowContext(ctx, createCurrencyPreference,
		arg.CurrencyID,
		arg.UserID,
		arg.IsFavorite,
		arg.DisplayOrder,
	)
	var i UserCurrencyPreference
	err := row.Scan(
		&i.CurrencyID,
		&i.UserID,
		&i.IsFavorite,
		&i.DisplayOrder,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCurrencyPreference = `-- name: DeleteCurrencyPreference :exec
DELETE FROM user_currency_preferences
WHERE currency_id = $1 AND user_id = $2
`

type DeleteCurrencyPreferenceParams struct {
	CurrencyID int32
	UserID     int32
}

func (q *Queries) DeleteCurrencyPreference(ctx context.Context, arg DeleteCurrencyPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteCurrencyPreference, arg.CurrencyID, arg.UserID)
	return err
}

const getAllCurrencyPreferences = `-- name: GetAllCurrencyPreferences :many
SELECT currency_id, user_id, is_favorite, display_order, updated_at, created_at FROM user_currency_preferences
ORDER BY user_id, display_order ASC
`

func (q *Queries) GetAllCurrencyPreferences(ctx context.Context) ([]UserCurrencyPreference, error) {
	rows, err := q.db.QueryContext(ctx, getAllCurrencyPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCurrencyPreference
	for rows.Next() {
		var i UserCurrencyPreference
		if err := rows.Scan(
			&i.CurrencyID,
			&i.UserID,
			&i.IsFavorite,
			&i.DisplayOrder,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyPreferencesByCurrencyID = `-- name: GetCurrencyPreferencesByCurrencyID :many
SELECT currency_id, user_id, is_favorite, display_order, updated_at, created_at FROM user_currency_preferences
WHERE currency_id = $1
ORDER BY user_id ASC
`

func (q *Queries) GetCurrencyPreferencesByCurrencyID(ctx context.Context, currencyID int32) ([]UserCurrencyPreference, error) {
	rows, err := q.db.QueryContext(ctx, getCurrencyPreferencesByCurrencyID, currencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCurrencyPreference
	for rows.Next() {
		var i UserCurrencyPreference
		if err := rows.Scan(
			&i.CurrencyID,
			&i.UserID,
			&i.IsFavorite,
			&i.DisplayOrder,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyPreferencesByUserID = `-- name: GetCurrencyPreferencesByUserID :many
SELECT currency_id, user_id, is_favorite, display_order, updated_at, created_at FROM user_currency_preferences
WHERE user_id = $1
ORDER BY display_order ASC, created_at ASC
`

func (q *Queries) GetCurrencyPreferencesByUserID(ctx context.Context, userID int32) ([]UserCurrencyPreference, error) {
	rows, err := q.db.QueryContext(ctx, getCurrencyPreferencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCurrencyPreference
	for rows.Next() {
		var i UserCurrencyPreference
		if err := rows.Scan(
			&i.CurrencyID,
			&i.UserID,
			&i.IsFavorite,
			&i.DisplayOrder,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrencyPreference = `-- name: UpdateCurrencyPreference :one
UPDATE user_currency_preferences
SET
    is_favorite = COALESCE($1, is_favorite),
    display_order = COALESCE($2, display_order),
    updated_at = CURRENT_TIMESTAMP
WHERE currency_id = $3 AND user_id = $4
RETURNING currency_id, user_id, is_favorite, display_order, updated_at, created_at
`

type UpdateCurrencyPreferenceParams struct {
	IsFavorite   sql.NullBool
	DisplayOrder sql.NullInt32
	CurrencyID   int32
	UserID       int32
}

func (q *Queries) UpdateCurrencyPreference(ctx context.Context, arg UpdateCurrencyPreferenceParams) (UserCurrencyPreference, error) {
	row := q.db.QueryRowContext(ctx, updateCurrencyPreference,
		arg.IsFavorite,
		arg.DisplayOrder,
		arg.CurrencyID,
		arg.UserID,
	)
	var i UserCurrencyPreference
	err := row.Scan(
		&i.CurrencyID,
		&i.UserID,
		&i.IsFavorite,
		&i.DisplayOrder,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
