// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: exchange_rate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatestExchangeRate struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RateId                  int32                  `protobuf:"varint,1,opt,name=rate_id,json=rateId,proto3" json:"rate_id,omitempty"`
	RateValue               string                 `protobuf:"bytes,2,opt,name=rate_value,json=rateValue,proto3" json:"rate_value,omitempty"`
	SourceCurrencyCode      string                 `protobuf:"bytes,3,opt,name=source_currency_code,json=sourceCurrencyCode,proto3" json:"source_currency_code,omitempty"`
	DestinationCurrencyCode string                 `protobuf:"bytes,4,opt,name=destination_currency_code,json=destinationCurrencyCode,proto3" json:"destination_currency_code,omitempty"`
	ValidFromDate           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_from_date,json=validFromDate,proto3" json:"valid_from_date,omitempty"`
	RateSourceCode          string                 `protobuf:"bytes,6,opt,name=rate_source_code,json=rateSourceCode,proto3" json:"rate_source_code,omitempty"`
	TypeName                string                 `protobuf:"bytes,7,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LatestExchangeRate) Reset() {
	*x = LatestExchangeRate{}
	mi := &file_exchange_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestExchangeRate) ProtoMessage() {}

func (x *LatestExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestExchangeRate.ProtoReflect.Descriptor instead.
func (*LatestExchangeRate) Descriptor() ([]byte, []int) {
	return file_exchange_rate_proto_rawDescGZIP(), []int{0}
}

func (x *LatestExchangeRate) GetRateId() int32 {
	if x != nil {
		return x.RateId
	}
	return 0
}

func (x *LatestExchangeRate) GetRateValue() string {
	if x != nil {
		return x.RateValue
	}
	return ""
}

func (x *LatestExchangeRate) GetSourceCurrencyCode() string {
	if x != nil {
		return x.SourceCurrencyCode
	}
	return ""
}

func (x *LatestExchangeRate) GetDestinationCurrencyCode() string {
	if x != nil {
		return x.DestinationCurrencyCode
	}
	return ""
}

func (x *LatestExchangeRate) GetValidFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFromDate
	}
	return nil
}

func (x *LatestExchangeRate) GetRateSourceCode() string {
	if x != nil {
		return x.RateSourceCode
	}
	return ""
}

func (x *LatestExchangeRate) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *LatestExchangeRate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_exchange_rate_proto protoreflect.FileDescriptor

const file_exchange_rate_proto_rawDesc = "" +
	"\n" +
	"\x13exchange_rate.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\x12LatestExchangeRate\x12\x17\n" +
	"\arate_id\x18\x01 \x01(\x05R\x06rateId\x12\x1d\n" +
	"\n" +
	"rate_value\x18\x02 \x01(\tR\trateValue\x120\n" +
	"\x14source_currency_code\x18\x03 \x01(\tR\x12sourceCurrencyCode\x12:\n" +
	"\x19destination_currency_code\x18\x04 \x01(\tR\x17destinationCurrencyCode\x12B\n" +
	"\x0fvalid_from_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rvalidFromDate\x12(\n" +
	"\x10rate_source_code\x18\x06 \x01(\tR\x0erateSourceCode\x12\x1b\n" +
	"\ttype_name\x18\a \x01(\tR\btypeName\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB(Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var (
	file_exchange_rate_proto_rawDescOnce sync.Once
	file_exchange_rate_proto_rawDescData []byte
)

func file_exchange_rate_proto_rawDescGZIP() []byte {
	file_exchange_rate_proto_rawDescOnce.Do(func() {
		file_exchange_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_rate_proto_rawDesc), len(file_exchange_rate_proto_rawDesc)))
	})
	return file_exchange_rate_proto_rawDescData
}

var file_exchange_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exchange_rate_proto_goTypes = []any{
	(*LatestExchangeRate)(nil),    // 0: pb.LatestExchangeRate
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_exchange_rate_proto_depIdxs = []int32{
	1, // 0: pb.LatestExchangeRate.valid_from_date:type_name -> google.protobuf.Timestamp
	1, // 1: pb.LatestExchangeRate.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exchange_rate_proto_init() }
func file_exchange_rate_proto_init() {
	if File_exchange_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_rate_proto_rawDesc), len(file_exchange_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exchange_rate_proto_goTypes,
		DependencyIndexes: file_exchange_rate_proto_depIdxs,
		MessageInfos:      file_exchange_rate_proto_msgTypes,
	}.Build()
	File_exchange_rate_proto = out.File
	file_exchange_rate_proto_goTypes = nil
	file_exchange_rate_proto_depIdxs = nil
}
