// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_signin_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInUserRequest) Reset() {
	*x = SignInUserRequest{}
	mi := &file_rpc_signin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInUserRequest) ProtoMessage() {}

func (x *SignInUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_signin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInUserRequest.ProtoReflect.Descriptor instead.
func (*SignInUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_signin_user_proto_rawDescGZIP(), []int{0}
}

func (x *SignInUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInUserResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	User                  *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId             string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken           string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignInUserResponse) Reset() {
	*x = SignInUserResponse{}
	mi := &file_rpc_signin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInUserResponse) ProtoMessage() {}

func (x *SignInUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_signin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInUserResponse.ProtoReflect.Descriptor instead.
func (*SignInUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_signin_user_proto_rawDescGZIP(), []int{1}
}

func (x *SignInUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SignInUserResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignInUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SignInUserResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SignInUserResponse) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *SignInUserResponse) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

var File_rpc_signin_user_proto protoreflect.FileDescriptor

const file_rpc_signin_user_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_signin_user.proto\x12\x02pb\x1a\n" +
	"user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x11SignInUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc1\x02\n" +
	"\x12SignInUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.pb.UserR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAtB(Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var (
	file_rpc_signin_user_proto_rawDescOnce sync.Once
	file_rpc_signin_user_proto_rawDescData []byte
)

func file_rpc_signin_user_proto_rawDescGZIP() []byte {
	file_rpc_signin_user_proto_rawDescOnce.Do(func() {
		file_rpc_signin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_signin_user_proto_rawDesc), len(file_rpc_signin_user_proto_rawDesc)))
	})
	return file_rpc_signin_user_proto_rawDescData
}

var file_rpc_signin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_signin_user_proto_goTypes = []any{
	(*SignInUserRequest)(nil),     // 0: pb.SignInUserRequest
	(*SignInUserResponse)(nil),    // 1: pb.SignInUserResponse
	(*User)(nil),                  // 2: pb.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_signin_user_proto_depIdxs = []int32{
	2, // 0: pb.SignInUserResponse.user:type_name -> pb.User
	3, // 1: pb.SignInUserResponse.access_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // 2: pb.SignInUserResponse.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_signin_user_proto_init() }
func file_rpc_signin_user_proto_init() {
	if File_rpc_signin_user_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_signin_user_proto_rawDesc), len(file_rpc_signin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_signin_user_proto_goTypes,
		DependencyIndexes: file_rpc_signin_user_proto_depIdxs,
		MessageInfos:      file_rpc_signin_user_proto_msgTypes,
	}.Build()
	File_rpc_signin_user_proto = out.File
	file_rpc_signin_user_proto_goTypes = nil
	file_rpc_signin_user_proto_depIdxs = nil
}
