// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_check_health.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_rpc_check_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_check_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_rpc_check_health_proto_rawDescGZIP(), []int{0}
}

type DependencyHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyHealth) Reset() {
	*x = DependencyHealth{}
	mi := &file_rpc_check_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyHealth) ProtoMessage() {}

func (x *DependencyHealth) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_check_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyHealth.ProtoReflect.Descriptor instead.
func (*DependencyHealth) Descriptor() ([]byte, []int) {
	return file_rpc_check_health_proto_rawDescGZIP(), []int{1}
}

func (x *DependencyHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DependencyHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Dependencies  []*DependencyHealth    `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_rpc_check_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_check_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_rpc_check_health_proto_rawDescGZIP(), []int{2}
}

func (x *CheckHealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CheckHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckHealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *CheckHealthResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *CheckHealthResponse) GetDependencies() []*DependencyHealth {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_rpc_check_health_proto protoreflect.FileDescriptor

const file_rpc_check_health_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_check_health.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12CheckHealthRequest\"X\n" +
	"\x10DependencyHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x86\x02\n" +
	"\x13CheckHealthResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x129\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x128\n" +
	"\fdependencies\x18\x06 \x03(\v2\x14.pb.DependencyHealthR\fdependenciesB(Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var (
	file_rpc_check_health_proto_rawDescOnce sync.Once
	file_rpc_check_health_proto_rawDescData []byte
)

func file_rpc_check_health_proto_rawDescGZIP() []byte {
	file_rpc_check_health_proto_rawDescOnce.Do(func() {
		file_rpc_check_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_check_health_proto_rawDesc), len(file_rpc_check_health_proto_rawDesc)))
	})
	return file_rpc_check_health_proto_rawDescData
}

var file_rpc_check_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_check_health_proto_goTypes = []any{
	(*CheckHealthRequest)(nil),    // 0: pb.CheckHealthRequest
	(*DependencyHealth)(nil),      // 1: pb.DependencyHealth
	(*CheckHealthResponse)(nil),   // 2: pb.CheckHealthResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_check_health_proto_depIdxs = []int32{
	3, // 0: pb.CheckHealthResponse.checked_at:type_name -> google.protobuf.Timestamp
	1, // 1: pb.CheckHealthResponse.dependencies:type_name -> pb.DependencyHealth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_check_health_proto_init() }
func file_rpc_check_health_proto_init() {
	if File_rpc_check_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_check_health_proto_rawDesc), len(file_rpc_check_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_check_health_proto_goTypes,
		DependencyIndexes: file_rpc_check_health_proto_depIdxs,
		MessageInfos:      file_rpc_check_health_proto_msgTypes,
	}.Build()
	File_rpc_check_health_proto = out.File
	file_rpc_check_health_proto_goTypes = nil
	file_rpc_check_health_proto_depIdxs = nil
}
