// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_get_latest_exchange_rates.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestExchangeRatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceCurrencyId int32                  `protobuf:"varint,1,opt,name=source_currency_id,json=sourceCurrencyId,proto3" json:"source_currency_id,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLatestExchangeRatesRequest) Reset() {
	*x = GetLatestExchangeRatesRequest{}
	mi := &file_rpc_get_latest_exchange_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestExchangeRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestExchangeRatesRequest) ProtoMessage() {}

func (x *GetLatestExchangeRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_latest_exchange_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestExchangeRatesRequest.ProtoReflect.Descriptor instead.
func (*GetLatestExchangeRatesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_latest_exchange_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestExchangeRatesRequest) GetSourceCurrencyId() int32 {
	if x != nil {
		return x.SourceCurrencyId
	}
	return 0
}

func (x *GetLatestExchangeRatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLatestExchangeRatesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LatestExchangeRates []*LatestExchangeRate  `protobuf:"bytes,1,rep,name=latest_exchange_rates,json=latestExchangeRates,proto3" json:"latest_exchange_rates,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetLatestExchangeRatesResponse) Reset() {
	*x = GetLatestExchangeRatesResponse{}
	mi := &file_rpc_get_latest_exchange_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestExchangeRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestExchangeRatesResponse) ProtoMessage() {}

func (x *GetLatestExchangeRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_latest_exchange_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestExchangeRatesResponse.ProtoReflect.Descriptor instead.
func (*GetLatestExchangeRatesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_latest_exchange_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestExchangeRatesResponse) GetLatestExchangeRates() []*LatestExchangeRate {
	if x != nil {
		return x.LatestExchangeRates
	}
	return nil
}

var File_rpc_get_latest_exchange_rates_proto protoreflect.FileDescriptor

const file_rpc_get_latest_exchange_rates_proto_rawDesc = "" +
	"\n" +
	"#rpc_get_latest_exchange_rates.proto\x12\x02pb\x1a\x13exchange_rate.proto\"c\n" +
	"\x1dGetLatestExchangeRatesRequest\x12,\n" +
	"\x12source_currency_id\x18\x01 \x01(\x05R\x10sourceCurrencyId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"l\n" +
	"\x1eGetLatestExchangeRatesResponse\x12J\n" +
	"\x15latest_exchange_rates\x18\x01 \x03(\v2\x16.pb.LatestExchangeRateR\x13latestExchangeRatesB(Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var (
	file_rpc_get_latest_exchange_rates_proto_rawDescOnce sync.Once
	file_rpc_get_latest_exchange_rates_proto_rawDescData []byte
)

func file_rpc_get_latest_exchange_rates_proto_rawDescGZIP() []byte {
	file_rpc_get_latest_exchange_rates_proto_rawDescOnce.Do(func() {
		file_rpc_get_latest_exchange_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_latest_exchange_rates_proto_rawDesc), len(file_rpc_get_latest_exchange_rates_proto_rawDesc)))
	})
	return file_rpc_get_latest_exchange_rates_proto_rawDescData
}

var file_rpc_get_latest_exchange_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_latest_exchange_rates_proto_goTypes = []any{
	(*GetLatestExchangeRatesRequest)(nil),  // 0: pb.GetLatestExchangeRatesRequest
	(*GetLatestExchangeRatesResponse)(nil), // 1: pb.GetLatestExchangeRatesResponse
	(*LatestExchangeRate)(nil),             // 2: pb.LatestExchangeRate
}
var file_rpc_get_latest_exchange_rates_proto_depIdxs = []int32{
	2, // 0: pb.GetLatestExchangeRatesResponse.latest_exchange_rates:type_name -> pb.LatestExchangeRate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_latest_exchange_rates_proto_init() }
func file_rpc_get_latest_exchange_rates_proto_init() {
	if File_rpc_get_latest_exchange_rates_proto != nil {
		return
	}
	file_exchange_rate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_latest_exchange_rates_proto_rawDesc), len(file_rpc_get_latest_exchange_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_latest_exchange_rates_proto_goTypes,
		DependencyIndexes: file_rpc_get_latest_exchange_rates_proto_depIdxs,
		MessageInfos:      file_rpc_get_latest_exchange_rates_proto_msgTypes,
	}.Build()
	File_rpc_get_latest_exchange_rates_proto = out.File
	file_rpc_get_latest_exchange_rates_proto_goTypes = nil
	file_rpc_get_latest_exchange_rates_proto_depIdxs = nil
}
