// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service_rate_pulse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_rate_pulse_proto protoreflect.FileDescriptor

const file_service_rate_pulse_proto_rawDesc = "" +
	"\n" +
	"\x18service_rate_pulse.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x15rpc_signin_user.proto2\x90\x01\n" +
	"\x10RatePulseService\x12=\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x12=\n" +
	"\n" +
	"SignInUser\x12\x15.pb.SignInUserRequest\x1a\x16.pb.SignInUserResponse\"\x00B(Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var file_service_rate_pulse_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: pb.CreateUserRequest
	(*SignInUserRequest)(nil),  // 1: pb.SignInUserRequest
	(*CreateUserResponse)(nil), // 2: pb.CreateUserResponse
	(*SignInUserResponse)(nil), // 3: pb.SignInUserResponse
}
var file_service_rate_pulse_proto_depIdxs = []int32{
	0, // 0: pb.RatePulseService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.RatePulseService.SignInUser:input_type -> pb.SignInUserRequest
	2, // 2: pb.RatePulseService.CreateUser:output_type -> pb.CreateUserResponse
	3, // 3: pb.RatePulseService.SignInUser:output_type -> pb.SignInUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_rate_pulse_proto_init() }
func file_service_rate_pulse_proto_init() {
	if File_service_rate_pulse_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_signin_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_rate_pulse_proto_rawDesc), len(file_service_rate_pulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_rate_pulse_proto_goTypes,
		DependencyIndexes: file_service_rate_pulse_proto_depIdxs,
	}.Build()
	File_service_rate_pulse_proto = out.File
	file_service_rate_pulse_proto_goTypes = nil
	file_service_rate_pulse_proto_depIdxs = nil
}
