// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service_rate_pulse.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_rate_pulse_proto protoreflect.FileDescriptor

const file_service_rate_pulse_proto_rawDesc = "" +
	"\n" +
	"\x18service_rate_pulse.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x15rpc_signin_user.proto\x1a#rpc_get_latest_exchange_rates.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x9e\x01\n" +
	"\x1eRatePulseAuthenticationService\x12=\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x12=\n" +
	"\n" +
	"SignInUser\x12\x15.pb.SignInUserRequest\x1a\x16.pb.SignInUserResponse\"\x002\x81\x01\n" +
	"\x1cRatePulseExchangeRateService\x12a\n" +
	"\x16GetLatestExchangeRates\x12!.pb.GetLatestExchangeRatesRequest\x1a\".pb.GetLatestExchangeRatesResponse\"\x00B\x95\x01\x92Aj\x12h\n" +
	"\x15Rate Pulse API - GRPC\"J\n" +
	"\x12Rate Pulse project\x12\x19https://www.rate-pulse.me\x1a\x19vinhtongthanh57@gmail.com2\x031.0Z&github.com/ThanhVinhTong/rate-pulse/pbb\x06proto3"

var file_service_rate_pulse_proto_goTypes = []any{
	(*CreateUserRequest)(nil),              // 0: pb.CreateUserRequest
	(*SignInUserRequest)(nil),              // 1: pb.SignInUserRequest
	(*GetLatestExchangeRatesRequest)(nil),  // 2: pb.GetLatestExchangeRatesRequest
	(*CreateUserResponse)(nil),             // 3: pb.CreateUserResponse
	(*SignInUserResponse)(nil),             // 4: pb.SignInUserResponse
	(*GetLatestExchangeRatesResponse)(nil), // 5: pb.GetLatestExchangeRatesResponse
}
var file_service_rate_pulse_proto_depIdxs = []int32{
	0, // 0: pb.RatePulseAuthenticationService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.RatePulseAuthenticationService.SignInUser:input_type -> pb.SignInUserRequest
	2, // 2: pb.RatePulseExchangeRateService.GetLatestExchangeRates:input_type -> pb.GetLatestExchangeRatesRequest
	3, // 3: pb.RatePulseAuthenticationService.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.RatePulseAuthenticationService.SignInUser:output_type -> pb.SignInUserResponse
	5, // 5: pb.RatePulseExchangeRateService.GetLatestExchangeRates:output_type -> pb.GetLatestExchangeRatesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_rate_pulse_proto_init() }
func file_service_rate_pulse_proto_init() {
	if File_service_rate_pulse_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_signin_user_proto_init()
	file_rpc_get_latest_exchange_rates_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_rate_pulse_proto_rawDesc), len(file_service_rate_pulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_rate_pulse_proto_goTypes,
		DependencyIndexes: file_service_rate_pulse_proto_depIdxs,
	}.Build()
	File_service_rate_pulse_proto = out.File
	file_service_rate_pulse_proto_goTypes = nil
	file_service_rate_pulse_proto_depIdxs = nil
}
