// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service_rate_pulse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatePulseAuthenticationService_CreateUser_FullMethodName = "/pb.RatePulseAuthenticationService/CreateUser"
	RatePulseAuthenticationService_SignInUser_FullMethodName = "/pb.RatePulseAuthenticationService/SignInUser"
)

// RatePulseAuthenticationServiceClient is the client API for RatePulseAuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatePulseAuthenticationServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	SignInUser(ctx context.Context, in *SignInUserRequest, opts ...grpc.CallOption) (*SignInUserResponse, error)
}

type ratePulseAuthenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatePulseAuthenticationServiceClient(cc grpc.ClientConnInterface) RatePulseAuthenticationServiceClient {
	return &ratePulseAuthenticationServiceClient{cc}
}

func (c *ratePulseAuthenticationServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, RatePulseAuthenticationService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratePulseAuthenticationServiceClient) SignInUser(ctx context.Context, in *SignInUserRequest, opts ...grpc.CallOption) (*SignInUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInUserResponse)
	err := c.cc.Invoke(ctx, RatePulseAuthenticationService_SignInUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatePulseAuthenticationServiceServer is the server API for RatePulseAuthenticationService service.
// All implementations must embed UnimplementedRatePulseAuthenticationServiceServer
// for forward compatibility.
type RatePulseAuthenticationServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	SignInUser(context.Context, *SignInUserRequest) (*SignInUserResponse, error)
	mustEmbedUnimplementedRatePulseAuthenticationServiceServer()
}

// UnimplementedRatePulseAuthenticationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatePulseAuthenticationServiceServer struct{}

func (UnimplementedRatePulseAuthenticationServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRatePulseAuthenticationServiceServer) SignInUser(context.Context, *SignInUserRequest) (*SignInUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignInUser not implemented")
}
func (UnimplementedRatePulseAuthenticationServiceServer) mustEmbedUnimplementedRatePulseAuthenticationServiceServer() {
}
func (UnimplementedRatePulseAuthenticationServiceServer) testEmbeddedByValue() {}

// UnsafeRatePulseAuthenticationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatePulseAuthenticationServiceServer will
// result in compilation errors.
type UnsafeRatePulseAuthenticationServiceServer interface {
	mustEmbedUnimplementedRatePulseAuthenticationServiceServer()
}

func RegisterRatePulseAuthenticationServiceServer(s grpc.ServiceRegistrar, srv RatePulseAuthenticationServiceServer) {
	// If the following call panics, it indicates UnimplementedRatePulseAuthenticationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatePulseAuthenticationService_ServiceDesc, srv)
}

func _RatePulseAuthenticationService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatePulseAuthenticationServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatePulseAuthenticationService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatePulseAuthenticationServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatePulseAuthenticationService_SignInUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatePulseAuthenticationServiceServer).SignInUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatePulseAuthenticationService_SignInUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatePulseAuthenticationServiceServer).SignInUser(ctx, req.(*SignInUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatePulseAuthenticationService_ServiceDesc is the grpc.ServiceDesc for RatePulseAuthenticationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatePulseAuthenticationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RatePulseAuthenticationService",
	HandlerType: (*RatePulseAuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _RatePulseAuthenticationService_CreateUser_Handler,
		},
		{
			MethodName: "SignInUser",
			Handler:    _RatePulseAuthenticationService_SignInUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_rate_pulse.proto",
}

const (
	RatePulseExchangeRateService_GetLatestExchangeRates_FullMethodName = "/pb.RatePulseExchangeRateService/GetLatestExchangeRates"
)

// RatePulseExchangeRateServiceClient is the client API for RatePulseExchangeRateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatePulseExchangeRateServiceClient interface {
	GetLatestExchangeRates(ctx context.Context, in *GetLatestExchangeRatesRequest, opts ...grpc.CallOption) (*GetLatestExchangeRatesResponse, error)
}

type ratePulseExchangeRateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatePulseExchangeRateServiceClient(cc grpc.ClientConnInterface) RatePulseExchangeRateServiceClient {
	return &ratePulseExchangeRateServiceClient{cc}
}

func (c *ratePulseExchangeRateServiceClient) GetLatestExchangeRates(ctx context.Context, in *GetLatestExchangeRatesRequest, opts ...grpc.CallOption) (*GetLatestExchangeRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestExchangeRatesResponse)
	err := c.cc.Invoke(ctx, RatePulseExchangeRateService_GetLatestExchangeRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatePulseExchangeRateServiceServer is the server API for RatePulseExchangeRateService service.
// All implementations must embed UnimplementedRatePulseExchangeRateServiceServer
// for forward compatibility.
type RatePulseExchangeRateServiceServer interface {
	GetLatestExchangeRates(context.Context, *GetLatestExchangeRatesRequest) (*GetLatestExchangeRatesResponse, error)
	mustEmbedUnimplementedRatePulseExchangeRateServiceServer()
}

// UnimplementedRatePulseExchangeRateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatePulseExchangeRateServiceServer struct{}

func (UnimplementedRatePulseExchangeRateServiceServer) GetLatestExchangeRates(context.Context, *GetLatestExchangeRatesRequest) (*GetLatestExchangeRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestExchangeRates not implemented")
}
func (UnimplementedRatePulseExchangeRateServiceServer) mustEmbedUnimplementedRatePulseExchangeRateServiceServer() {
}
func (UnimplementedRatePulseExchangeRateServiceServer) testEmbeddedByValue() {}

// UnsafeRatePulseExchangeRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatePulseExchangeRateServiceServer will
// result in compilation errors.
type UnsafeRatePulseExchangeRateServiceServer interface {
	mustEmbedUnimplementedRatePulseExchangeRateServiceServer()
}

func RegisterRatePulseExchangeRateServiceServer(s grpc.ServiceRegistrar, srv RatePulseExchangeRateServiceServer) {
	// If the following call panics, it indicates UnimplementedRatePulseExchangeRateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatePulseExchangeRateService_ServiceDesc, srv)
}

func _RatePulseExchangeRateService_GetLatestExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatePulseExchangeRateServiceServer).GetLatestExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatePulseExchangeRateService_GetLatestExchangeRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatePulseExchangeRateServiceServer).GetLatestExchangeRates(ctx, req.(*GetLatestExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatePulseExchangeRateService_ServiceDesc is the grpc.ServiceDesc for RatePulseExchangeRateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatePulseExchangeRateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RatePulseExchangeRateService",
	HandlerType: (*RatePulseExchangeRateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestExchangeRates",
			Handler:    _RatePulseExchangeRateService_GetLatestExchangeRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_rate_pulse.proto",
}
