// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service_rate_pulse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatePulseService_CreateUser_FullMethodName = "/pb.RatePulseService/CreateUser"
	RatePulseService_SignInUser_FullMethodName = "/pb.RatePulseService/SignInUser"
)

// RatePulseServiceClient is the client API for RatePulseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatePulseServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	SignInUser(ctx context.Context, in *SignInUserRequest, opts ...grpc.CallOption) (*SignInUserResponse, error)
}

type ratePulseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatePulseServiceClient(cc grpc.ClientConnInterface) RatePulseServiceClient {
	return &ratePulseServiceClient{cc}
}

func (c *ratePulseServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, RatePulseService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratePulseServiceClient) SignInUser(ctx context.Context, in *SignInUserRequest, opts ...grpc.CallOption) (*SignInUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInUserResponse)
	err := c.cc.Invoke(ctx, RatePulseService_SignInUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatePulseServiceServer is the server API for RatePulseService service.
// All implementations must embed UnimplementedRatePulseServiceServer
// for forward compatibility.
type RatePulseServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	SignInUser(context.Context, *SignInUserRequest) (*SignInUserResponse, error)
	mustEmbedUnimplementedRatePulseServiceServer()
}

// UnimplementedRatePulseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatePulseServiceServer struct{}

func (UnimplementedRatePulseServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRatePulseServiceServer) SignInUser(context.Context, *SignInUserRequest) (*SignInUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignInUser not implemented")
}
func (UnimplementedRatePulseServiceServer) mustEmbedUnimplementedRatePulseServiceServer() {}
func (UnimplementedRatePulseServiceServer) testEmbeddedByValue()                          {}

// UnsafeRatePulseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatePulseServiceServer will
// result in compilation errors.
type UnsafeRatePulseServiceServer interface {
	mustEmbedUnimplementedRatePulseServiceServer()
}

func RegisterRatePulseServiceServer(s grpc.ServiceRegistrar, srv RatePulseServiceServer) {
	// If the following call panics, it indicates UnimplementedRatePulseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatePulseService_ServiceDesc, srv)
}

func _RatePulseService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatePulseServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatePulseService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatePulseServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatePulseService_SignInUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatePulseServiceServer).SignInUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatePulseService_SignInUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatePulseServiceServer).SignInUser(ctx, req.(*SignInUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatePulseService_ServiceDesc is the grpc.ServiceDesc for RatePulseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatePulseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RatePulseService",
	HandlerType: (*RatePulseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _RatePulseService_CreateUser_Handler,
		},
		{
			MethodName: "SignInUser",
			Handler:    _RatePulseService_SignInUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_rate_pulse.proto",
}
