apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-pulse-worker-deployment
  labels:
    app: rate-pulse-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-pulse-worker
  template:
    metadata:
      labels:
        app: rate-pulse-worker
    spec:
      imagePullSecrets:
        - name: dockerhub-pull
      containers:
      - name: rate-pulse-worker
        image: vinhtongthanh57/rate-pulse-api:latest
        envFrom:
        - secretRef:
            name: rate-pulse-secrets
        env:
        - name: ENABLE_HTTP_SERVER
          value: "false"
        - name: ENABLE_GRPC_SERVER
          value: "false"
        - name: ENABLE_TASK_PROCESSOR
          value: "true"