name: Deploy pulse-intel to production

on:
  pull_request:
    branches: [main]
    paths:
      - "pulse-intel/**"
      - ".github/workflows/deploy-pulse-intel.yml"
  push:
    branches: [main]
    paths:
      - "pulse-intel/**"
      - ".github/workflows/deploy-pulse-intel.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vinhtongthanh57/rate-pulse-intel
      IMAGE_TAG: ${{ github.sha }}