name: Client CI

on:
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy-client.yml"
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy-client.yml"
  workflow_dispatch:

jobs:
  ci:
    name: Lint and Build Client
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Temporary suspended to fix
      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run build
